"""How the writing actually reads, measured over what has been written.

Run against the development database, which is where every chapter this product
has ever generated lives:

    .venv/bin/python tools/prose_report.py            # every locale
    .venv/bin/python tools/prose_report.py --locale ru
    .venv/bin/python tools/prose_report.py --since 2026-08-08   # after a change

**Why this exists.** The owner's verdict on his own chapters was that they are
ornate and machine-made — «многие люди, кто захочет с этим поработать, просто
не смогут почитать» — and the only honest answer to that is a number, before
and after. Measured on 8 August 2026 over 124 Russian paragraphs, before the
plain-language rules landed:

    dashes per paragraph   2.72
    words per sentence     16.2
    "дом" 143 · "квадрат" 21 · "асцендент" 15 · "модальность"/"стихия" 15

The targets are the ones `alma/ai/validator.py` gates on and `voice.py` asks
for: the language's own dash budget, about fourteen words a sentence, none of
the words that sound like meaning and carry none. Russian is allowed two dashes
where every other language gets one — it has no present-tense copula, so
«Сатурн — планета границ» has nowhere else to put the verb.

This is a report and not a test. It reads what was generated by a real model
against a real chart, which no test can do — and it is worth exactly what
re-running it costs, which is nothing.
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import statistics
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from alma.ai.validator import SENTENCE_CEILING, _PURPLE, dash_budget  # noqa: E402

DB = Path(__file__).resolve().parents[1] / "data" / "alma.db"

#: Terms a reader without astrology cannot parse. Counted rather than banned:
#: some of them have to appear — a chapter about houses says "house" — and the
#: rule in `voice.py` is that the word is explained in something checkable, not
#: that it is absent. A rising count here is still worth looking at.
JARGON = (
    "дом", "квадрат", "асцендент", "стихи", "модальност", "орб", "ретроград",
    "оппозици", "соединени", "секстиль", "трин", "куспид", "десцендент",
    "середина неба", "аркан", "управител",
)


def paragraphs(row: str) -> list[str]:
    try:
        payload = json.loads(row)
    except (TypeError, ValueError):
        return []
    body = payload.get("body") if isinstance(payload, dict) else payload
    return [p for p in (body or []) if isinstance(p, str) and p.strip()]


def report(locale: str | None, since: str | None) -> int:
    if not DB.exists():
        print(f"no database at {DB}", file=sys.stderr)
        return 1

    query = "SELECT locale, body, created_at FROM reading"
    where, args = [], []
    if locale:
        where.append("locale = ?")
        args.append(locale)
    if since:
        where.append("created_at >= ?")
        args.append(since)
    if where:
        query += " WHERE " + " AND ".join(where)

    with sqlite3.connect(DB) as db:
        rows = db.execute(query, args).fetchall()

    by_locale: dict[str, list[str]] = {}
    for row_locale, body, _ in rows:
        by_locale.setdefault(row_locale, []).extend(paragraphs(body))

    if not by_locale:
        print("nothing written yet for that filter")
        return 0

    for row_locale in sorted(by_locale):
        paras = by_locale[row_locale]
        budget = dash_budget(row_locale)
        dashes = [p.count("—") + p.count("–") for p in paras]
        lengths: list[int] = []
        over_budget = 0
        for paragraph in paras:
            if paragraph.count("—") + paragraph.count("–") > budget:
                over_budget += 1
            for sentence in re.split(r"[.!?…]+", paragraph):
                if sentence.strip():
                    lengths.append(len(sentence.split()))

        joined = " ".join(paras).lower()
        purple = Counter()
        for word in _PURPLE.get(row_locale, _PURPLE.get(row_locale.split("-")[0], ())):
            found = joined.count(word)
            if found:
                purple[word] = found

        print(f"\n── {row_locale} · {len(paras)} paragraphs · {sum(lengths)} words")
        mean_dashes = statistics.mean(dashes) if dashes else 0
        mean_words = statistics.mean(lengths) if lengths else 0
        print(f"   dashes per paragraph   {mean_dashes:.2f}"
              f"   (budget {budget}; {over_budget} paragraphs over)")
        print(f"   words per sentence     {mean_words:.1f}"
              f"   (gate {SENTENCE_CEILING:.0f}, target ~14)")
        if lengths:
            print(f"   longest sentence       {max(lengths)} words")
        if purple:
            print("   words that carry nothing: "
                  + ", ".join(f"{w}×{n}" for w, n in purple.most_common(8)))
        else:
            print("   words that carry nothing: none")

        if row_locale == "ru":
            hits = Counter()
            for term in JARGON:
                found = joined.count(term)
                if found:
                    hits[term] = found
            if hits:
                print("   unexplained terms (counted, not banned): "
                      + ", ".join(f"{w}×{n}" for w, n in hits.most_common(8)))
    print()
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--locale", help="only this locale")
    parser.add_argument("--since", help="ISO date; only readings written after it")
    parsed = parser.parse_args()
    raise SystemExit(report(parsed.locale, parsed.since))
