"""The funnel — the one table in this schema that was never written to.

Every conversion figure the pricing work stands on is an assumption until
these rows exist, so what is tested here is not "does a POST return 200". It
is the six properties that decide whether the numbers can be believed:

* a name outside the closed set never becomes a row, because one typo is a
  cohort that silently vanishes from a query nobody re-checks;
* the browser cannot claim a purchase, because that number decides how much
  money is spent on advertising;
* somebody who has told us nothing is counted, because most of this funnel
  happens in front of the sign-in wall and a funnel that starts at sign-in
  measures the wrong product — **and counting them does not enrol them**, which
  is the rule this route used to break on every page load;
* the browser id and the account minted out of it are one person, because a
  funnel whose halves cannot be joined has traded one broken measurement for
  another and reads 0% on data that looks healthy;
* deletion and retention reach the rows recorded before the account existed,
  because those are the ones that do not carry its id;
* and the arithmetic — of the people who reached A, how many reached B — is
  right on a seeded set whose answer can be read off by hand.
"""

from __future__ import annotations

import asyncio
from datetime import timedelta

import pytest
from conftest import database_url, read_async, run_async
from sqlalchemy import select

from alma import funnel
from alma.db.models import AnonymousVisitor, Event, Purchase, User, new_id, utcnow
from tests.conftest import SOFIA


# ── the endpoint ──────────────────────────────────────────────────────────


def _events(api) -> list[Event]:
    """Every row in the table, for a test that has just made some HTTP calls."""
    from alma.db.session import session_factory

    async def read():
        async with session_factory()() as session:
            return (await session.execute(select(Event))).scalars().all()

    return read_async(read)


def test_a_stage_we_do_not_know_never_becomes_a_row(api, auth_headers):
    """A misspelt stage is refused, and the refusal says what to send instead.

    The whole value of the table is that every row can be counted. `offerView`
    accepted alongside `offer_view` is two cohorts, one of which converts at
    zero, and nothing about the resulting number looks wrong.
    """
    refused = api.post(
        "/v1/events", json={"stage": "offer_veiw"}, headers=auth_headers
    )
    assert refused.status_code == 422
    detail = refused.json()["detail"]
    assert detail["error"] == "unknown_stage"
    assert "offer_view" in detail["stages"]
    assert _events(api) == []


def test_the_browser_cannot_report_a_purchase(api, auth_headers):
    """Money is known at the webhook. Anything else is a number anyone can set."""
    refused = api.post(
        "/v1/events",
        json={"stage": "purchase", "properties": {"product": "bundle.static"}},
        headers=auth_headers,
    )
    assert refused.status_code == 422
    assert refused.json()["detail"]["error"] == "server_recorded"
    assert _events(api) == []


def _users(api) -> list[User]:
    """Every account in the database. Usually the interesting number is zero."""
    from alma.db.session import session_factory

    async def read():
        async with session_factory()() as session:
            return (await session.execute(select(User))).scalars().all()

    return read_async(read)


#: What a client sends to say which browser this is. One id, generated by the
#: client, kept for the life of the browser's storage.
ANON = {"X-Alma-Anon": "3f9a4c1e-77b2-4d0a-9c31-0f8e6b2a5d44"}


def test_a_visitor_who_has_given_us_nothing_is_measured_and_not_enrolled(api):
    """The stage is recorded. No account exists afterwards.

    This is the whole change, in one assertion pair. A visitor who has told us
    nothing is most of this funnel — if the top of it could only be recorded for
    people with accounts, every rate below it would be divided by a number from
    a different product — but *recording* somebody and *enrolling* them are
    different acts, and this route used to do both. The landing fires on mount,
    so a browser that loaded the page and touched nothing left a user row
    behind, and two thirds of the rows in the dev database were that.
    """
    recorded = api.post("/v1/events", json={"stage": "landing_view"}, headers=ANON)
    assert recorded.status_code == 200
    assert recorded.json() == {"recorded": True, "stage": "landing_view"}

    # Nothing was minted, so there is nothing to hand back.
    assert "X-Alma-Token" not in recorded.headers
    assert _users(api) == []

    rows = _events(api)
    assert len(rows) == 1
    assert rows[0].name == "landing_view"
    assert rows[0].user_id is None
    assert rows[0].anon_id == ANON["X-Alma-Anon"]


def test_a_stage_with_nothing_behind_it_at_all_is_refused(api):
    """No token, no id: there is nothing to count this against, and we say so.

    The alternative is a row with two nulls in it, which counts towards
    `count(*)` and towards no funnel — a table that answers differently
    depending on who queries it. Our own clients cannot reach this, because each
    of them has an id before it makes its first request; a client written
    against the old shape of this route can, and a message naming the header it
    is missing is more use to whoever has to fix it than a 200 that discarded
    the event.
    """
    refused = api.post("/v1/events", json={"stage": "landing_view"})
    assert refused.status_code == 422
    detail = refused.json()["detail"]
    assert detail["error"] == "anonymous_id_required"
    assert detail["header"] == "X-Alma-Anon"
    assert _events(api) == []
    assert _users(api) == []


def test_an_id_that_could_be_something_a_person_typed_is_not_stored(api, auth_headers):
    """`X-Alma-Anon` is a header on a table that holds nothing personal.

    A column reached from a browser header is a column somebody's address ends
    up in — by a well-meaning client putting an email in it to "improve
    attribution", which is exactly how the properties bag would have acquired a
    birth date if it had not been an allowlist. So an id that does not look like
    one we would have issued is treated as absent rather than stored, and here
    that leaves a perfectly good event attributed to the account that sent it.
    """
    sent = api.post(
        "/v1/events",
        json={"stage": "landing_view"},
        headers={**auth_headers, "X-Alma-Anon": "sofia@example.com"},
    )
    assert sent.status_code == 200
    assert _events(api)[0].anon_id is None


def test_saving_a_birth_is_what_creates_the_account(api):
    """The act, and the only thing in this test that mints anything.

    The visitor walks two rungs of the funnel with no account and then saves a
    birth. That is the first moment they have given us something to keep, so it
    is the first moment there is a row — and the token comes back on *that*
    response rather than on a page view.
    """
    for stage in ("landing_view", "quiz_start"):
        assert api.post("/v1/events", json={"stage": stage}, headers=ANON).status_code == 200
    assert _users(api) == []

    saved = api.post("/v1/profiles", json=SOFIA, headers=ANON)
    assert saved.status_code == 201
    assert saved.headers["X-Alma-Token"]

    accounts = _users(api)
    assert len(accounts) == 1
    assert accounts[0].is_guest


#: Every route the landing page calls without anybody touching anything, in the
#: order a browser actually issues them. The catalogue goes first because
#: `<Pricing />` is rendered unconditionally and `useCatalogue` fetches in an
#: effect, which lands before the beacon does — the ordering is the reason this
#: is a list rather than a single call, since the route that mints on a page
#: view is whichever one happens to be first.
ON_MOUNT = (
    ("GET", "/v1/billing/catalogue"),
    ("POST", "/v1/events"),
)


def test_loading_the_landing_page_creates_nothing(api):
    """Every request a page view makes, and no account at the end of them.

    This is the owner's rule — an account is created by registering or by going
    through the journey, *not* by a page view — asserted against the whole set
    of calls a page view makes rather than against the one route that was blamed
    for it. `POST /v1/events` was fixed and `GET /v1/billing/catalogue` was not,
    so a browser that loaded the site and touched nothing still came away with a
    `user` row and a bearer token for it; the 143-accounts-against-46-profiles
    ratio would simply have been reproduced through the other door.

    Asserting no `X-Alma-Token` on any response matters as much as asserting no
    row: `src/lib/api.ts` adopts that header from *any* response, so a route
    that mints hands the visitor a durable credential for an account they never
    asked for, and every later request in that browser carries it.
    """
    for method, path in ON_MOUNT:
        answered = (
            api.get(path, headers=ANON)
            if method == "GET"
            else api.post(path, json={"stage": "landing_view"}, headers=ANON)
        )
        assert answered.status_code == 200, f"{method} {path} answered {answered.status_code}"
        assert "X-Alma-Token" not in answered.headers, f"{method} {path} minted an account"

    assert _users(api) == []


def test_a_price_list_says_the_same_thing_to_a_visitor_and_a_fresh_account(api, auth_headers):
    """Taking `Visitor` changed the account it creates, not the answer it gives.

    The two values the route reads off a person are a recent purchase's credit
    and the systems already unlocked, and both are empty for an account minted a
    microsecond ago — so if the response differed at all, the fix would have
    been a behaviour change wearing a refactor's clothes, and the pricing
    section would quietly show a visitor something different from what it shows
    the same visitor one act later.
    """
    anonymous = api.get("/v1/billing/catalogue", headers=ANON)
    enrolled = api.get("/v1/billing/catalogue", headers=auth_headers)

    assert anonymous.status_code == enrolled.status_code == 200
    assert anonymous.json() == enrolled.json()
    assert anonymous.json()["unlocked"] == []


def _funnel_over(api) -> dict[str, funnel.Step]:
    """The report, read out of the database an HTTP test has just filled."""
    from alma.db.session import session_factory

    async def read():
        async with session_factory()() as session:
            return await funnel.funnel(session)

    return {step.stage: step for step in read_async(read)}


def test_the_journey_is_one_person_across_the_account_it_creates(api):
    """The whole point of the anonymous id, end to end over HTTP.

    Two stages before there is an account, an account created by saving a birth,
    two stages after it. Six rows in two names, and the answer that matters is
    that the landing view and the portrait belong to **one** person: "of the
    people who saw the landing, how many finished the journey" is the number the
    pricing model rests on, and if the id in the browser could not be attached
    to the account minted out of it, this would read one person arriving and a
    different person converting — 0% and 100% at once, on data that looks
    perfectly healthy.

    Which is why this walks the real routes rather than seeding rows. The join
    is made by `deps.current_user` at the moment `POST /v1/profiles` mints, and
    a test that called `funnel.claim` itself would be asserting that a function
    it just ran does what it does.
    """
    for stage in ("landing_view", "quiz_start"):
        assert api.post("/v1/events", json={"stage": stage}, headers=ANON).status_code == 200

    saved = api.post("/v1/profiles", json=SOFIA, headers=ANON)
    assert saved.status_code == 201
    token = saved.headers["X-Alma-Token"]

    # From here the client has both: the token it was just given, and the id it
    # has been carrying since before the account existed.
    signed = {**ANON, "Authorization": f"Bearer {token}"}
    for stage in ("quiz_complete", "portrait_view"):
        assert api.post("/v1/events", json={"stage": stage}, headers=signed).status_code == 200

    steps = _funnel_over(api)
    assert steps["landing_view"].reached == 1
    assert steps["quiz_start"].reached == 1
    assert steps["quiz_complete"].reached == 1
    assert steps["portrait_view"].reached == 1
    # Every rate is one person out of one person. A broken join reads 0.0 here,
    # which is the shape of the bug and the reason to assert the rate and not
    # only the count.
    assert steps["portrait_view"].rate == 1.0
    # And nobody arrived in the middle: `total` equal to `reached` is what says
    # the two halves were folded rather than counted twice.
    assert steps["landing_view"].total == 1
    assert steps["portrait_view"].total == 1


def test_the_visitor_and_the_account_it_became_are_not_two_people(db):
    """The same fold, at the level of the module, with the halves seeded apart.

    The HTTP test above proves the wiring. This one pins the rule: an id that
    has been claimed resolves to the account that claimed it, so a stage
    recorded before the account and a stage recorded after it are one identity —
    and it stays true through a merge, because a guest who signs into an account
    they already had is the second indirection on the same row.
    """
    async def seed(session):
        guest, existing = _person(session), _person(session)
        await session.flush()

        await funnel.record(session, user_id=None, anon_id="browser-one", stage="landing_view")
        await funnel.record(session, user_id=None, anon_id="browser-one", stage="quiz_start")
        assert await funnel.claim(session, anon_id="browser-one", user_id=guest.id)
        await _walk(session, guest, "quiz_complete")

        # And then they signed in on a laptop, into an account they already had.
        guest.merged_into_id = existing.id
        await _walk(session, existing, "portrait_view")
        await session.flush()
        return await funnel.funnel(session)

    steps = _steps(_run(db, seed))
    assert steps["landing_view"].reached == 1
    assert steps["portrait_view"].reached == 1
    assert steps["portrait_view"].rate == 1.0


def test_an_unclaimed_visitor_is_counted_rather_than_dropped(db):
    """Somebody who looked and left is the denominator, not a rounding error.

    They have no account and never will, so the only thing there is to count
    them by is the id their browser sent. Dropping those rows — the obvious
    reading of "attribute events to accounts" — deletes everybody who has not
    converted, and every conversion rate in the report goes to 100%.
    """
    async def seed(session):
        for browser in ("one", "two", "three"):
            await funnel.record(
                session, user_id=None, anon_id=f"browser-{browser}", stage="landing_view"
            )
        buyer = _person(session)
        await session.flush()
        await funnel.claim(session, anon_id="browser-one", user_id=buyer.id)
        await _walk(session, buyer, "quiz_start")
        return await funnel.funnel(session)

    steps = _steps(_run(db, seed))
    assert steps["landing_view"].reached == 3
    assert steps["quiz_start"].reached == 1
    assert steps["quiz_start"].rate == 1 / 3


def test_the_next_person_at_a_shared_browser_is_not_the_last_one(db):
    """A claim covers the rows before it, and nothing that arrives long after.

    The family computer, which is the ordinary case rather than the edge one.
    The first person's account is minted out of this browser and the id is
    claimed for it. Somebody else then sits down, arrives with no token — the id
    outlives one person's session — and walks the top of the funnel again.

    Resolving every bare id to whichever account once claimed it made those rows
    the *first* person's: they improved a conversion rate they were not part of,
    the second person could not ask for them back because they belong to an
    account that is not theirs, and the first person's erasure took them out
    from under them. So the second visit is counted as what it is — somebody we
    cannot name — while the first person's own pre-account journey, which is the
    entire reason the claim exists, still folds onto their account.
    """
    async def seed(session):
        first = _person(session)
        await session.flush()

        await funnel.record(session, user_id=None, anon_id="the-family-mac", stage="landing_view")
        assert await funnel.claim(session, anon_id="the-family-mac", user_id=first.id)
        await _walk(session, first, "quiz_start", "quiz_complete")

        # Somebody else, next morning, same machine, no token.
        later = utcnow() + funnel.CLAIM_GRACE + timedelta(hours=12)
        for stage in ("landing_view", "quiz_start"):
            row = await funnel.record(
                session, user_id=None, anon_id="the-family-mac", stage=stage
            )
            row.created_at = later
        await session.flush()
        return await funnel.audience(session), first.id

    reached, first = _run(db, seed)

    # Two people saw the landing, and only one of them is an account.
    assert reached["landing_view"] == {first, "anon:the-family-mac"}
    # The second person's quiz_start is theirs. Folded onto the first person it
    # would have been invisible — they had already reached that stage.
    assert reached["quiz_start"] == {first, "anon:the-family-mac"}
    # And the first person's own journey still joins across the account it made.
    assert reached["quiz_complete"] == {first}


def test_the_beacon_that_was_in_flight_when_the_account_appeared_still_counts(db):
    """The reason the boundary is a window rather than the claim instant.

    `quiz_complete` is fired by the same screen that saves the birth, and a
    `keepalive` request outlives the page that started it, so the beacon and the
    request that mints can cross on the wire. Drawing the line at the exact
    moment of the claim would drop the last rung before conversion — the one the
    whole report is read for — on a perfectly ordinary journey, and it would do
    it intermittently, which is worse than doing it always.
    """
    async def seed(session):
        person = _person(session)
        await session.flush()

        await funnel.record(session, user_id=None, anon_id="one-browser", stage="landing_view")
        assert await funnel.claim(session, anon_id="one-browser", user_id=person.id)

        # Landed after the claim, sent before it, carrying no token because the
        # response that issued one had not arrived yet.
        crossed = await funnel.record(
            session, user_id=None, anon_id="one-browser", stage="quiz_complete"
        )
        crossed.created_at = utcnow() + timedelta(seconds=30)
        await session.flush()
        return await funnel.audience(session), person.id

    reached, person = _run(db, seed)
    assert reached["quiz_complete"] == {person}


def test_the_first_account_to_claim_an_id_keeps_it(db):
    """A second account does not inherit the first one's history.

    Two things lead here — a race between two tokenless requests, and a shared
    browser whose second person signs in — and re-pointing the id would move one
    person's landing view onto the other person's account, silently and
    plausibly. First claim wins means the second account is missing stages it
    never had, which shows up as a gap between `reached` and `total`.
    """
    async def seed(session):
        first, second = _person(session), _person(session)
        await session.flush()
        assert await funnel.claim(session, anon_id="shared-browser", user_id=first.id) is True
        assert await funnel.claim(session, anon_id="shared-browser", user_id=second.id) is False
        owner = await session.get(AnonymousVisitor, "shared-browser")
        return owner.user_id, first.id

    owner, first = _run(db, seed)
    assert owner == first


def test_an_id_that_is_not_one_never_reaches_the_table(db):
    """`clean_anon_id` is the allowlist for the second identifier.

    The properties bag has one because a free-form bag is how a birth date
    arrives; this header needs one for the same reason and one more — it is the
    column an operator would reach for to "improve attribution" by putting
    something recognisable in it.
    """
    assert funnel.clean_anon_id("3f9a4c1e-77b2-4d0a-9c31-0f8e6b2a5d44")
    assert funnel.clean_anon_id("  padded-but-fine-0123  ") == "padded-but-fine-0123"
    assert funnel.clean_anon_id("sofia@example.com") is None
    assert funnel.clean_anon_id("Sofia Bianchi") is None
    assert funnel.clean_anon_id("short") is None          # too short to be random
    assert funnel.clean_anon_id("x" * 65) is None
    assert funnel.clean_anon_id(None) is None
    assert funnel.clean_anon_id("") is None

    async def attempt(session):
        with pytest.raises(funnel.Unattributed):
            await funnel.record(
                session, user_id=None, anon_id="sofia@example.com", stage="landing_view"
            )
        with pytest.raises(funnel.Unattributed):
            await funnel.record(session, user_id=None, anon_id=None, stage="landing_view")
        assert (await session.execute(select(Event))).scalars().all() == []

    _run(db, attempt)


def test_a_visitor_cannot_be_used_as_a_write_amplifier(api, monkeypatch):
    """The ceiling applies to somebody with no account to count it against.

    Otherwise the whole cap is opt-in: it lived in a per-account counter table,
    and a caller who no longer needs an account to write rows would have been
    handed an unmetered endpoint by the same change that stopped minting.
    """
    monkeypatch.setattr(funnel, "DAILY_LIMIT", 2)

    for _ in range(2):
        assert api.post(
            "/v1/events", json={"stage": "landing_view"}, headers=ANON
        ).status_code == 200

    refused = api.post("/v1/events", json={"stage": "quiz_start"}, headers=ANON)
    assert refused.status_code == 429
    assert refused.json()["detail"]["error"] == "event_rate_limit"
    assert len(_events(api)) == 2

    # A different browser is a different allowance — the cap bounds one
    # visitor's rows, and one shared ceiling would let anybody switch the
    # measurement off for everybody else.
    other = api.post(
        "/v1/events",
        json={"stage": "landing_view"},
        headers={"X-Alma-Anon": "a-completely-different-browser-id"},
    )
    assert other.status_code == 200


def test_an_account_cannot_be_used_as_a_write_amplifier(api, auth_headers, monkeypatch):
    """Past the day's allowance the answer is 429 and nothing is written.

    The cap is monkeypatched rather than exercised at its real value: what is
    being asserted is that there *is* a ceiling and that crossing it costs a
    row, not the particular integer, which is a product decision that will move.
    """
    monkeypatch.setattr(funnel, "DAILY_LIMIT", 3)

    for _ in range(3):
        assert api.post(
            "/v1/events", json={"stage": "landing_view"}, headers=auth_headers
        ).status_code == 200

    refused = api.post("/v1/events", json={"stage": "quiz_start"}, headers=auth_headers)
    assert refused.status_code == 429
    assert refused.json()["detail"]["error"] == "event_rate_limit"
    assert len(_events(api)) == 3

    # And the refusal is stable rather than a one-off: what the ceiling counts
    # is rows already in the table, so being turned away does not clear it.
    assert api.post(
        "/v1/events", json={"stage": "quiz_start"}, headers=auth_headers
    ).status_code == 429
    assert len(_events(api)) == 3


def test_only_labels_about_the_product_may_be_attached(api, auth_headers):
    """The allowlist is the thing keeping birth data out of an analytics table.

    The unwanted label is dropped and the event survives, which is the opposite
    of what happens to an unwanted stage name. An unknown stage has nowhere to
    be counted, so refusing it costs nothing; an unknown label on a good stage
    would cost the whole row, and this client throws away every error it gets —
    so a rung of the funnel would vanish for a release and nothing would say so.
    """
    kept = api.post(
        "/v1/events",
        json={"stage": "offer_view", "meta": {"system": "natal", "locale": "de"}},
        headers=auth_headers,
    )
    assert kept.status_code == 200
    assert _events(api)[0].properties == {"system": "natal", "locale": "de"}

    smuggled = api.post(
        "/v1/events",
        json={"stage": "quiz_complete", "meta": {"system": "natal", "birth_time": "04:20"}},
        headers=auth_headers,
    )
    assert smuggled.status_code == 200
    stored = [row for row in _events(api) if row.name == "quiz_complete"]
    assert stored[0].properties == {"system": "natal"}


def test_a_label_long_enough_to_be_a_sentence_is_dropped_whole(api, auth_headers):
    """A label is a slug. Half of somebody's address is still their address."""
    sent = api.post(
        "/v1/events",
        json={"stage": "offer_view", "meta": {"variant": "x" * 200, "product": "sub.monthly"}},
        headers=auth_headers,
    )
    assert sent.status_code == 200
    assert _events(api)[0].properties == {"product": "sub.monthly"}


def test_a_label_that_is_something_a_person_typed_never_reaches_the_table(api, auth_headers):
    """A short value on an allowed key was enough, and short is not the rule.

    `{"variant": "Sofia Bianchi"}` is fourteen characters; `{"how":
    "sofia@example.com"}` is seventeen. Both were on the allowlist, both were
    under the ceiling, and both were written verbatim into an analytics table
    whose entire stated discipline is that nothing a person typed can be in it —
    the privacy page's list is short and complete only if that is true. It was
    true of the browser, because `scrub` in `src/lib/track.ts` refused them
    before they left; it was not true of the column.

    Posted over HTTP rather than asserted against `clean_properties` directly,
    because the thing being claimed is about what can end up in the table, and a
    second client, a curl or a future screen all arrive this way.
    """
    sent = api.post(
        "/v1/events",
        json={
            "stage": "offer_view",
            "meta": {
                "variant": "Sofia Bianchi",
                "how": "sofia@example.com",
                "chapter": "why am I like this",
                "product": "sub.monthly",
            },
        },
        headers=auth_headers,
    )
    assert sent.status_code == 200, sent.json()
    # The good label survives: one bad dimension must never cost the rung.
    assert _events(api)[0].properties == {"product": "sub.monthly"}


def test_the_two_ends_of_the_wire_keep_the_same_values(api, auth_headers):
    """Not just the same keys — the same verdict on each value.

    `test_the_labels_the_client_keeps_are_the_labels_the_server_keeps` ties the
    allowlists together and stops there, and the two ends disagreed underneath
    it for as long as that test has existed: the client tested its values
    against a label pattern and the server only measured their length. A
    disagreement in this direction is invisible from either side — the browser
    silently sends less than it is allowed to, and the server silently accepts
    more than it says it does — so the rule itself is read out of the shipped
    client and both ends are asked about the same battery of values.
    """
    import re

    declared = re.search(r"const LABEL = /(.+?)/;", _client_source())
    assert declared, "src/lib/track.ts no longer declares a LABEL pattern this can read"
    client = re.compile(declared.group(1))

    candidates = [
        "natal",
        "pt-BR",
        "archive-upgrade",
        "solar_return",
        "USD",
        "7",
        "skipped",
        "x" * 64,
        # And the ones neither end may keep.
        "x" * 65,
        "",
        "Sofia Bianchi",
        "sofia@example.com",
        " natal ",
        "-leading-dash",
        "natal/chapter",
    ]

    for value in candidates:
        kept_by_server = funnel.clean_properties({"variant": value})
        kept_by_client = bool(client.fullmatch(value))
        assert bool(kept_by_server) == kept_by_client, value
        if kept_by_client:
            # And kept *as sent*: a server that tidied a value into shape would
            # store something the client would have refused outright.
            assert kept_by_server == {"variant": value}, value


def _client_source() -> str:
    """`src/lib/track.ts`, or a skip when the interface is not in this checkout.

    Read rather than restated. The previous version of the two tests below held
    a hand-copied list of stage names and property keys, and a hand-copied list
    is exactly what produced the divergence they existed to catch: the client
    shipped `declined` while the server's closed set said `offer_declined`, the
    beacon swallowed the 422, and the test certified a vocabulary nobody sent.
    """
    from pathlib import Path

    source = Path(__file__).resolve().parents[2] / "src" / "lib" / "track.ts"
    if not source.exists():
        pytest.skip("the interface is not in this checkout")
    return source.read_text(encoding="utf-8")


def test_the_client_that_ships_is_the_client_that_is_accepted(api, auth_headers):
    """Every stage `src/lib/track.ts` can send, read out of the file itself.

    A beacon swallows its own failures, so a disagreement between the two ends
    of this wire is invisible in production — not a 500 in a log, just a rung of
    the funnel that reads zero for ever on data that looks perfectly healthy.
    Which is why this posts the names the client actually declares rather than
    the names anybody believes it declares.
    """
    import re

    union = re.search(r"export type Stage =\s*((?:\s*\|\s*\"[a-z_]+\")+)", _client_source())
    assert union, "src/lib/track.ts no longer declares a Stage union this can read"
    stages = re.findall(r'"([a-z_]+)"', union.group(1))
    assert stages, "the Stage union is empty"

    for stage in stages:
        sent = api.post(
            "/v1/events",
            json={"stage": stage, "meta": {"product": "bundle.static"}},
            headers=auth_headers,
        )
        assert sent.status_code == 200, (stage, sent.json())

    assert len(_events(api)) == len(stages)


def test_the_labels_the_client_keeps_are_the_labels_the_server_keeps():
    """`KEYS` in the client mirrors `PROPERTIES` here, and it says so itself.

    A key the client strips is a dimension that silently never arrives; a key
    the server does not know is dropped and logged. Neither is fatal on its own,
    which is precisely why the two lists drift — so the invariant the client's
    own docstring states is checked rather than trusted.
    """
    import re

    block = re.search(r"const KEYS = new Set\(\[(.*?)\]\)", _client_source(), re.S)
    assert block, "src/lib/track.ts no longer declares a KEYS allowlist"
    assert set(re.findall(r'"([a-z_]+)"', block.group(1))) == funnel.PROPERTIES


def test_the_header_the_client_sends_is_the_header_the_server_reads():
    """Read out of `src/lib/api.ts`, for the reason the two tests above are.

    A header name is the easiest thing on this wire to get wrong and the hardest
    to notice: the beacon swallows the 422, and every visitor without an account
    silently stops being counted while the rows from people who *do* have one
    keep arriving — so the funnel does not empty, it just quietly starts
    measuring only the people who already converted.
    """
    import re
    from pathlib import Path

    from alma.api.deps import ANON_ID_HEADER

    source = Path(__file__).resolve().parents[2] / "src" / "lib" / "api.ts"
    if not source.exists():
        pytest.skip("the interface is not in this checkout")

    declared = re.search(
        r'export const ANON_HEADER = "([^"]+)"', source.read_text(encoding="utf-8")
    )
    assert declared, "src/lib/api.ts no longer declares ANON_HEADER"
    assert declared.group(1).lower() == ANON_ID_HEADER.lower()


def test_both_apps_send_the_header_this_server_reads():
    """The same rule for iOS and Android, where it matters more.

    The web is a storefront; the product ships as two native apps, so the
    surface this header actually has to arrive from is the one nobody can check
    by opening a browser. And the failure is silent in the same way: the beacon
    swallows its 422, so a misspelt constant does not empty the funnel — it
    quietly leaves it measuring only the installs that already have an account,
    which is to say only the people who already converted.
    """
    import re
    from pathlib import Path

    from alma.api.deps import ANON_ID_HEADER

    root = Path(__file__).resolve().parents[2] / "mobile"
    clients = {
        "iOS": (
            root / "ios" / "Alma" / "Networking" / "AlmaClient.swift",
            r'static let anonHeader = "([^"]+)"',
        ),
        "Android": (
            root / "android" / "app" / "src" / "main" / "kotlin" / "ai" / "pazl" / "alma"
            / "data" / "AlmaHttp.kt",
            r'const val ANON_HEADER = "([^"]+)"',
        ),
    }

    for platform, (source, pattern) in clients.items():
        if not source.exists():
            pytest.skip(f"the {platform} app is not in this checkout")
        declared = re.search(pattern, source.read_text(encoding="utf-8"))
        assert declared, f"{platform} no longer declares the anonymous-id header"
        assert declared.group(1).lower() == ANON_ID_HEADER.lower(), platform


def test_opening_the_app_and_closing_it_leaves_nothing_behind(api):
    """The web's rule, on the surface where almost every real user is.

    `GET /v1/auth/session` mints for a caller with no token, and that is correct
    — it is one of the acts. What was wrong is that both apps called it on
    launch, unconditionally, so an install that opened the app and closed it
    again left an account behind: 100% of installs, before anybody had typed
    anything, which is the same arithmetic that turned "how many accounts are
    there" into a count of downloads on the web.

    Two halves, and this is the first: **the route really does mint**, so the
    guard in each app is load-bearing rather than decorative. If this route ever
    stopped creating, the second half of this test would keep passing while
    guarding nothing, and nobody would know the apps had been carrying a check
    they no longer needed.
    """
    assert _users(api) == []
    minted = api.get("/v1/auth/session")
    assert minted.status_code == 200
    assert len(_users(api)) == 1
    assert minted.headers.get("X-Alma-Token")


def test_neither_app_calls_a_minting_route_before_it_has_a_token():
    """The second half: on both platforms, launch reads and does not create.

    Source is read rather than behaviour observed, and the reason is the shape
    of this repository rather than a preference — the Python suite is the only
    gate that runs on every change, and the thing being defended is a property
    of two codebases it cannot import. The alternative was to leave the rule
    unasserted on the two clients that account for every real install, which is
    how it came to be broken on both of them in the first place.

    What is checked is an *ordering*, not a spelling of the fix: inside the
    launch path, the check that a token already exists comes before the call
    that would mint one, and it returns. A rename fails this loudly, which is
    the correct outcome — somebody renaming the guard should have to say so.

    The four calls a launch makes are covered by that one ordering. `profiles`,
    `entitlements` and `hub` all take `CurrentUser` on the server too, so any of
    them would mint the row the session call is being kept away from; both apps
    put them after the early return, and a rearrangement that moved one above it
    would move it above the guard as well.
    """
    from pathlib import Path

    root = Path(__file__).resolve().parents[2] / "mobile"
    apps = {
        "iOS": (
            root / "ios" / "Alma" / "State" / "AlmaSessionModel.swift",
            "func start() async {",
            "guard client.hasAccount else {",
            "client.session()",
        ),
        "Android": (
            root / "android" / "app" / "src" / "main" / "kotlin" / "ai" / "pazl" / "alma"
            / "core" / "SessionHolder.kt",
            "fun start(",
            "!client.hasSession",
            "client.session()",
        ),
    }

    for platform, (source, launch, guard, mints) in apps.items():
        if not source.exists():
            pytest.skip(f"the {platform} app is not in this checkout")
        text = source.read_text(encoding="utf-8")

        for marker in (launch, guard, mints):
            assert marker in text, f"{platform}: {marker!r} is no longer in {source.name}"

        assert text.index(launch) < text.index(guard) < text.index(mints), (
            f"{platform}: the launch path reaches a minting call before it has "
            "checked whether this install already has a token"
        )
        # And the guard has to *stop*, not merely observe. A branch that logs
        # and falls through is the bug with a comment on it.
        assert "return" in text[text.index(guard) : text.index(mints)], (
            f"{platform}: the token check does not return before the minting call"
        )


def test_a_checkout_is_recorded_by_the_server_that_opened_it(api, auth_headers, monkeypatch):
    """`checkout_opened` used to exist only on the browser's word.

    Which means a buyer with Do Not Track or Global Privacy Control set produced
    a purchase with no checkout above it: they fell out of the nested count, and
    the one conversion rate that decides advertising spend was computed on a
    denominator that systematically excluded privacy-conscious buyers. Duplicate
    rows from the beacon are harmless — the funnel counts distinct accounts.
    """
    from alma.api.routers import billing as router
    from alma.billing.paddle import PaddleProvider
    from alma.billing.provider import SessionHandle, stamp

    class Opens(PaddleProvider):
        async def open_session(self, *, product, user_id, currency, country=None, email=None):
            return SessionHandle(
                provider="paddle", product=product, currency=currency,
                cents=899, display="$8.99", custom_data=stamp(user_id, product),
            )

    from alma import config as config_module

    monkeypatch.setenv("PADDLE_WEBHOOK_SECRET", "pdl_ntfset_test")
    monkeypatch.setenv("PADDLE_API_KEY", "pdl_test")
    config_module.settings.cache_clear()
    monkeypatch.setattr(router, "billing_adapter", lambda *_, **__: Opens())
    try:
        opened = api.post(
            "/v1/billing/checkout", json={"product": "door.natal"}, headers=auth_headers
        )
        assert opened.status_code == 200
    finally:
        config_module.settings.cache_clear()

    rows = _events(api)
    assert [(row.name, row.properties.get("product")) for row in rows] == [
        ("checkout_opened", "door.natal")
    ]


def test_the_column_name_works_on_the_wire_too(api, auth_headers):
    """`properties` is what the column is called, so a caller may send that."""
    sent = api.post(
        "/v1/events",
        json={"stage": "offer_view", "properties": {"product": "sub.monthly"}},
        headers=auth_headers,
    )
    assert sent.status_code == 200
    assert _events(api)[0].properties == {"product": "sub.monthly"}


# ── лестница монетизации (§7 ТЗ v3) ───────────────────────────────────────
#
# Одиннадцать событий, которые шлёт клиент, с полями, которые §7 им называет,
# и с поверхностью из §3 на каждом. Двенадцатое имя §7 — `purchase`: оно
# записывается из платёжной записи и здесь проверяется тем, что по-прежнему
# отбивается (см. `test_money_stays_the_webhooks_word_in_v3_too`).
#
# Словарь один на все проверки нарочно: событие, которое кто-то заведёт в
# `STAGES` и забудет здесь, роняет `test_the_ladder_this_file_covers_is_the_whole_ladder`
# — то есть новый пейволл не может приехать в прод без строки в отчёте.
LADDER: dict[str, dict] = {
    "paywall_shown": {
        "surface": "p1",
        "sku": "door.natal",
        "trigger": "chapter_end",
        "nbo_reason": "interest_love",
    },
    "paywall_dismissed": {"surface": "p1", "method": "swipe"},
    "checkout_started": {"surface": "p2", "sku": "bundle.static", "price": "19.99"},
    "free_chapter_completed": {"surface": "p1", "system": "natal"},
    "partner_added": {"surface": "p4"},
    "pair_teaser_completed": {"surface": "p4"},
    "question_quota_hit": {"surface": "p6"},
    "cancel_flow_entered": {"surface": "p8"},
    "save_offer_shown": {"surface": "p8", "sku": "door.natal"},
    "save_offer_accepted": {"surface": "p8", "sku": "door.natal"},
    "push_opened": {"surface": "p9", "type": "daily"},
}


@pytest.mark.parametrize("stage", sorted(LADDER))
def test_every_event_of_the_ladder_is_accepted_with_the_fields_the_brief_gives_it(
    api, auth_headers, stage
):
    """Принимается — и сохраняется целиком, а не наполовину.

    Второе важнее первого. Ярлык, который сервер молча выбросил, стоит той же
    дыры в отчёте, что и отказ, только увидеть её нельзя ниоткуда: клиент
    получил 200, строка в таблице есть, а измерения в ней нет. Поэтому здесь
    сверяется весь мешок целиком, а не код ответа.
    """
    sent = api.post("/v1/events", json={"stage": stage, "meta": LADDER[stage]}, headers=auth_headers)
    assert sent.status_code == 200, sent.json()

    rows = _events(api)
    assert len(rows) == 1
    assert rows[0].name == stage
    assert rows[0].properties == LADDER[stage]


def test_the_ladder_this_file_covers_is_the_whole_ladder():
    """Каждое событие лестницы имеет здесь строку — иначе тест краснеет.

    Без этой проверки предыдущий тест покрывает ровно то, что кто-то не забыл
    в него дописать, а забывают всегда новое: событие заводят в `STAGES` под
    новый экран, тестов на него нет, и в отчёте оно потом читается как ноль.
    """
    assert set(LADDER) == {stage.name for stage in funnel.STAGES if stage.monetization}


@pytest.mark.parametrize("stage", sorted(LADDER))
def test_no_event_of_the_ladder_is_recorded_without_saying_where_it_happened(
    api, auth_headers, stage
):
    """Гейт §А12, по одному событию за раз: без `surface` строки не будет.

    Отказ, а не строка с пустым местом, и не подстановка «unknown». Эти
    двенадцать имён заводились ради сравнения поверхностей: `paywall_shown`,
    сложенный по всем экранам, — счётчик пейволлов вообще, и решение «какой
    пейволл убрать» по нему принимать нельзя. Значение по умолчанию выполнило
    бы гейт формально и создало бы в таблице ведро, означающее «клиент забыл»,
    которое ни один отчёт не отличит от настоящей поверхности.
    """
    without = {key: value for key, value in LADDER[stage].items() if key != "surface"}
    refused = api.post("/v1/events", json={"stage": stage, "meta": without}, headers=auth_headers)

    assert refused.status_code == 422, refused.json()
    detail = refused.json()["detail"]
    assert detail["error"] == "surface_required"
    # Список отдаётся обратно: ошибся клиент, ему и показывать слова.
    assert "p1" in detail["surfaces"]
    assert _events(api) == []


def test_a_surface_this_product_does_not_have_is_refused_rather_than_stored(api, auth_headers):
    """`paywall_p1` — не поверхность, и это отдельный ответ от «поля нет».

    Две разные починки в клиенте: там забыли поле, здесь прислали своё слово
    вместо кода §3. Один общий отказ отправил бы автора искать не туда.

    Хранить такое нельзя по той же причине, по которой нельзя хранить опечатку
    в имени ступени: `p1` и `paywall_p1` в одной колонке — две когорты, одна из
    которых конвертируется в ноль, и в отчёте это выглядит здоровым.
    """
    refused = api.post(
        "/v1/events",
        json={"stage": "paywall_shown", "meta": {"surface": "paywall_p1", "sku": "door.natal"}},
        headers=auth_headers,
    )
    assert refused.status_code == 422
    detail = refused.json()["detail"]
    assert detail["error"] == "unknown_surface"
    assert detail["surfaces"] == list(funnel.SURFACES)

    # И то, что поверхностью вообще не является: число вместо кода — это
    # «прислали не то», а не «не прислали ничего».
    number = api.post(
        "/v1/events",
        json={"stage": "paywall_shown", "meta": {"surface": 1}},
        headers=auth_headers,
    )
    assert number.status_code == 422
    assert number.json()["detail"]["error"] == "unknown_surface"

    assert _events(api) == []


def test_the_case_the_brief_writes_is_not_a_second_cohort(api, auth_headers):
    """ТЗ пишет `P1`, таблица хранит `p1`, и это одна ступень, а не две.

    Разбор члена перечисления — не подчистка значения: ярлыки этот модуль не
    правит нигде (половина чьего-то адреса — всё ещё его адрес). Здесь
    приводится только регистр, и ровно затем, чтобы отчёт не разъехался на
    `p1` и `P1` из-за того, как поверхность названа в документе.
    """
    sent = api.post(
        "/v1/events",
        json={"stage": "question_quota_hit", "meta": {"surface": " P6 "}},
        headers=auth_headers,
    )
    assert sent.status_code == 200, sent.json()
    assert _events(api)[0].properties == {"surface": "p6"}


def test_money_stays_the_webhooks_word_in_v3_too(api, auth_headers):
    """§7 просит `purchase{sku, surface, price}` — и это по-прежнему 422.

    Двенадцатое событие §7 уже есть в закрытом наборе и помечено
    `server_known`: деньги знает подписанная нотификация стора, а не телефон.
    Новая спецификация эту дверь не открывает — иначе число, по которому решают
    рекламный бюджет, стало бы полем, которое любой может прислать курлом.
    Поверхность продажи читается из `checkout_started` того же человека.
    """
    refused = api.post(
        "/v1/events",
        json={
            "stage": "purchase",
            "meta": {"sku": "sub.monthly", "surface": "p5", "price": "9.99"},
        },
        headers=auth_headers,
    )
    assert refused.status_code == 422
    assert refused.json()["detail"]["error"] == "server_recorded"
    assert _events(api) == []


def test_the_ladders_labels_belong_to_the_ladder_and_not_to_the_rest(api, auth_headers):
    """`sku` на `paywall_shown` — размерность; на `offer_view` — мусор.

    `PROPERTIES` — общий словарь с вебом, слово в слово (`KEYS` в
    `src/lib/track.ts`, и это проверяет соседний тест). Веб заморожен на
    четырёх ступенях v2 и ни одной из этих поверхностей не имеет, так что ключ,
    который он не пришлёт никогда, не должен расширять мешок, об который
    чистится каждый маяк лендинга: чем шире общий список, тем меньше он значит.

    Выброшено, а не отказано, — как любой незнакомый ярлык: ступень при этом
    выживает, потому что маяк своё 422 глотает молча и рунг исчез бы целиком.
    """
    ladder = api.post(
        "/v1/events",
        json={"stage": "paywall_shown", "meta": {"surface": "p5", "sku": "sub.monthly"}},
        headers=auth_headers,
    )
    assert ladder.status_code == 200
    assert _events(api)[0].properties == {"surface": "p5", "sku": "sub.monthly"}

    older = api.post(
        "/v1/events",
        json={"stage": "offer_view", "meta": {"sku": "sub.monthly", "product": "sub.monthly"}},
        headers=auth_headers,
    )
    assert older.status_code == 200
    stored = [row for row in _events(api) if row.name == "offer_view"]
    assert stored[0].properties == {"product": "sub.monthly"}


def test_the_two_allowlists_do_not_overlap():
    """Общий словарь с вебом и словарь лестницы не пересекаются, и это правило.

    Соседний тест сверяет `PROPERTIES` с `KEYS` из `src/lib/track.ts` на
    равенство. Дописать `surface` в `PROPERTIES` значит уронить его — но уронить
    его можно и молча, если однажды слить оба списка в один: тогда веб придётся
    трогать (он заморожен), либо равенство придётся ослабить до вложения, и
    вместе с ним пропадёт единственная проверка того, что два конца провода
    говорят одними словами.
    """
    assert not (funnel.PROPERTIES & funnel.MONETIZATION_PROPERTIES)


def test_a_ladder_label_that_is_something_a_person_typed_is_dropped_too(api, auth_headers):
    """Новые ключи проходят то же сито `LABEL`, что и старые.

    Приватность этой таблицы держится не на списке ключей, а на форме значений:
    ключ из белого списка со свободным текстом внутри — ровно то, как сюда
    попадает чьё-то имя. `nbo_reason` — самый вероятный кандидат: он про
    причину, а причину легко захотеть записать словами.
    """
    sent = api.post(
        "/v1/events",
        json={
            "stage": "paywall_shown",
            "meta": {
                "surface": "p3",
                "nbo_reason": "она читала главу про любовь",
                "trigger": "sofia@example.com",
                "sku": "pair.check",
            },
        },
        headers=auth_headers,
    )
    assert sent.status_code == 200, sent.json()
    # Поверхность и SKU выжили: одна плохая размерность не стоит ступени.
    assert _events(api)[0].properties == {"surface": "p3", "sku": "pair.check"}


def test_every_surface_is_a_label_this_table_can_keep():
    """Закрытый набор и правило значения не должны противоречить друг другу.

    Поверхность проходит `check_surface` и потом `clean_properties`. Член
    набора, не проходящий `LABEL`, дал бы 200 со строкой без поверхности — то
    есть ровно то, что гейт §А12 запрещает, но уже молча.
    """
    for surface in funnel.SURFACES:
        assert funnel.clean_properties(
            {"surface": surface}, stage="paywall_shown"
        ) == {"surface": surface}


def test_every_event_the_brief_names_is_an_event_this_server_knows():
    """§7 ТЗ читается из файла, а не пересказывается здесь.

    Список, переписанный руками, — это то, чем уже один раз кончилось на этом
    проводе: клиент слал `declined`, сервер знал `offer_declined`, маяк глотал
    422, и тест удостоверял словарь, которого никто не отправлял. Поэтому имена
    берутся из строки «События:» самого ТЗ — документа, по которому пишут и
    клиент, и этот файл.
    """
    import re
    from pathlib import Path

    brief = (
        Path(__file__).resolve().parents[2]
        / "docs" / "monetization" / "alma-monetization-v3-tz.md"
    )
    if not brief.exists():
        pytest.skip("ТЗ монетизации v3 не в этом чекауте")

    line = re.search(r"^События: (.+)$", brief.read_text(encoding="utf-8"), re.M)
    assert line, "§7 больше не начинает список со слова «События:»"

    named: list[str] = []
    for token in re.findall(r"`([a-z_]+(?:/[a-z_]+)?)(?:\{[^}]*\})?`", line.group(1)):
        if "/" in token:
            # `save_offer_shown/accepted` — сокращение ТЗ для пары событий с
            # общим началом. Разворачивается здесь, а не заводится третьим
            # именем на сервере.
            first, second = token.split("/", 1)
            named += [first, f"{first.rsplit('_', 1)[0]}_{second}"]
        else:
            named.append(token)

    assert len(named) >= 12, f"§7 разобрался не целиком: {named}"
    for name in named:
        assert name in funnel.BY_NAME, f"§7 называет {name!r}, сервер такого не знает"


# ── the query ─────────────────────────────────────────────────────────────


@pytest.fixture
def db(tmp_path, monkeypatch):
    """A database of our own, with no HTTP anywhere near it."""
    from alma import config as config_module
    from alma.db import session as session_module

    # Disposed before the URL is chosen: on Postgres `database_url` empties
    # the schema, and a connection still pooled from the previous test would
    # turn that drop into a lock wait.
    asyncio.run(session_module.dispose())
    monkeypatch.setenv("ALMA_DATABASE_URL", database_url(tmp_path, "funnel.db"))
    monkeypatch.setenv("ALMA_JWT_SECRET", "test-secret-not-the-default")
    config_module.settings.cache_clear()
    run_async(session_module.create_all)
    yield session_module
    asyncio.run(session_module.dispose())
    config_module.settings.cache_clear()


def _run(db, work):
    async def go():
        async with db.session_scope() as session:
            return await work(session)

    return run_async(go)


def _person(session) -> User:
    user = User(id=new_id(), provider="guest", locale="en")
    session.add(user)
    return user


async def _walk(session, user: User, *stages: str, surface: str = "p1") -> None:
    """Take one person as far down the funnel as the caller says.

    Событию лестницы поверхность подставляется, всем прочим — нет: `record`
    первое без неё не запишет, а второму выбросил бы ярлык как незнакомый.
    """
    for stage in stages:
        ladder = funnel.BY_NAME[stage].monetization
        await funnel.record(
            session,
            user_id=user.id,
            stage=stage,
            properties={"surface": surface} if ladder else None,
        )


def _steps(steps) -> dict[str, funnel.Step]:
    return {step.stage: step for step in steps}


def test_of_the_people_who_reached_a_how_many_reached_b(db):
    """Four in at the top, one out at the bottom, and every rate in between.

    The set is small enough that the answer can be read off by hand, which is
    the only way to know a funnel query is right: three people start the quiz,
    two finish it, one opens a checkout.
    """
    async def seed(session):
        everyone = [_person(session) for _ in range(4)]
        await session.flush()
        a, b, c, d = everyone
        await _walk(session, a, "landing_view", "quiz_start", "quiz_complete",
                    "portrait_view", "offer_view", "checkout_opened")
        await _walk(session, b, "landing_view", "quiz_start", "quiz_complete")
        await _walk(session, c, "landing_view", "quiz_start")
        await _walk(session, d, "landing_view")
        return await funnel.funnel(session)

    steps = _steps(_run(db, seed))

    assert steps["landing_view"].reached == 4
    assert steps["landing_view"].rate is None       # nothing above it to divide by
    assert steps["quiz_start"].reached == 3
    assert steps["quiz_start"].rate == 0.75
    assert steps["quiz_complete"].reached == 2
    assert steps["portrait_view"].reached == 1
    assert steps["checkout_opened"].reached == 1
    assert steps["purchase"].reached == 0
    assert steps["purchase"].rate == 0.0


def test_the_same_stage_twice_is_still_one_person(db):
    """Somebody who refreshes the landing page has not doubled the market."""
    async def seed(session):
        alone = _person(session)
        await session.flush()
        await _walk(session, alone, "landing_view", "landing_view", "landing_view")
        return await funnel.funnel(session)

    assert _steps(_run(db, seed))["landing_view"].reached == 1


def test_a_purchase_is_counted_from_the_money_not_from_a_beacon(db):
    """No event row says `purchase`. The funnel still knows about the sale.

    This is the same rule the endpoint enforces from the other side: the
    purchase stage is read from the row the signed webhook wrote, so it is true
    even for a payment reconciled by hand and cannot be inflated by a client.
    """
    async def seed(session):
        buyer = _person(session)
        await session.flush()
        await _walk(session, buyer, "landing_view", "quiz_start", "quiz_complete",
                    "portrait_view", "offer_view", "checkout_opened")
        session.add(
            Purchase(
                id=new_id(),
                user_id=buyer.id,
                provider="paddle",
                transaction_id="txn_paid",
                product="bundle.static",
                status="transaction.completed",
                amount_cents=3899,
                currency="USD",
                completed_at=utcnow(),
            )
        )
        # A checkout that was opened and never paid for. It has a purchase row
        # — the money trail keeps those — but no `completed_at`, and counting
        # it would report a sale that never happened.
        session.add(
            Purchase(
                id=new_id(),
                user_id=buyer.id,
                provider="paddle",
                transaction_id="txn_pending",
                product="bundle.static",
                status="pending",
                amount_cents=3899,
                currency="USD",
            )
        )
        return await funnel.funnel(session)

    steps = _steps(_run(db, seed))
    assert steps["purchase"].reached == 1
    assert steps["purchase"].rate == 1.0


def test_declined_is_measured_against_the_checkout_not_against_buying(db):
    """Two outcomes of one pay button, both divided by the same base.

    Read as a step below `purchase` it would be the people who declined *after*
    buying — always nobody, a zero indistinguishable from a broken beacon.
    """
    async def seed(session):
        buyer, walker = _person(session), _person(session)
        await session.flush()
        for person in (buyer, walker):
            await _walk(session, person, "landing_view", "quiz_start", "quiz_complete",
                        "portrait_view", "offer_view", "checkout_opened")
        await _walk(session, walker, "offer_declined")
        session.add(
            Purchase(
                id=new_id(), user_id=buyer.id, provider="paddle",
                transaction_id="txn_1", product="door.natal", status="completed",
                amount_cents=899, currency="USD", completed_at=utcnow(),
            )
        )
        return await funnel.funnel(session)

    steps = _steps(_run(db, seed))
    assert steps["offer_declined"].of == "checkout_opened"
    assert steps["offer_declined"].reached == 1
    assert steps["offer_declined"].rate == 0.5
    assert steps["purchase"].rate == 0.5


def test_an_overlay_that_finished_with_no_money_behind_it_is_visible(db):
    """The browser said it worked and no payment ever arrived.

    That gap is the reason the browser's word is a stage of its own rather than
    being thrown away: it is somebody who believes they have paid and has
    nothing, and it is invisible if the two facts are stored as one.
    """
    async def seed(session):
        paid, stranded = _person(session), _person(session)
        await session.flush()
        for person in (paid, stranded):
            await _walk(session, person, "landing_view", "quiz_start", "quiz_complete",
                        "portrait_view", "offer_view", "checkout_opened",
                        "purchase_completed")
        session.add(
            Purchase(
                id=new_id(), user_id=paid.id, provider="paddle",
                transaction_id="txn_real", product="bundle.static", status="completed",
                amount_cents=3899, currency="USD", completed_at=utcnow(),
            )
        )
        return await funnel.funnel(session)

    steps = _steps(_run(db, seed))
    assert steps["purchase_completed"].reached == 2
    assert steps["purchase"].reached == 1
    # Both measured against the checkout, so the shortfall is readable as one
    # subtraction rather than as a rate of a rate.
    assert steps["purchase"].of == steps["purchase_completed"].of == "checkout_opened"


def test_a_buyer_whose_browser_said_nothing_is_still_a_sale(db):
    """Do Not Track is honoured by the client, so the beacon never fires.

    If the purchase rung hung off `purchase_completed` instead of off the
    checkout, every customer with that switch set would disappear out of the
    revenue line — measurement quietly deciding who counts as a customer.
    """
    async def seed(session):
        quiet = _person(session)
        await session.flush()
        await _walk(session, quiet, "landing_view", "quiz_start", "quiz_complete",
                    "portrait_view", "offer_view", "checkout_opened")
        session.add(
            Purchase(
                id=new_id(), user_id=quiet.id, provider="dodo",
                transaction_id="txn_quiet", product="sub.monthly", status="completed",
                amount_cents=7899, currency="USD", completed_at=utcnow(),
            )
        )
        return await funnel.funnel(session)

    steps = _steps(_run(db, seed))
    assert steps["purchase_completed"].reached == 0
    assert steps["purchase"].reached == 1


def test_someone_who_arrived_in_the_middle_is_shown_rather_than_hidden(db):
    """A shared link starts at the portrait. The nested count must not eat them.

    `reached` follows the path and `total` does not, so the gap between the two
    is the signal that people are entering mid-funnel — which is a real thing
    that happens, and reporting only the nested number would read as traffic we
    never had.
    """
    async def seed(session):
        walker, linked = _person(session), _person(session)
        await session.flush()
        await _walk(session, walker, "landing_view", "quiz_start", "quiz_complete",
                    "portrait_view")
        await _walk(session, linked, "portrait_view")
        return await funnel.funnel(session)

    steps = _steps(_run(db, seed))
    assert steps["portrait_view"].reached == 1
    assert steps["portrait_view"].total == 2


def test_a_guest_who_signs_in_is_one_person_not_two(db):
    """The quiz happened on a phone as a guest; the purchase on a laptop account.

    `accounts.merge` folds one row into another and has never heard of this
    table, so without following the pointer the funnel sees a guest who did the
    quiz and never converted, plus an account that bought without ever seeing
    an offer. Both halves are wrong, in opposite directions.
    """
    async def seed(session):
        guest, account = _person(session), _person(session)
        await session.flush()
        await _walk(session, guest, "landing_view", "quiz_start", "quiz_complete",
                    "portrait_view", "offer_view")
        guest.merged_into_id = account.id
        await _walk(session, account, "checkout_opened")
        await session.flush()
        return await funnel.funnel(session)

    steps = _steps(_run(db, seed))
    assert steps["landing_view"].reached == 1
    assert steps["checkout_opened"].reached == 1
    assert steps["checkout_opened"].rate == 1.0


def test_the_window_is_the_window(db):
    """A funnel over thirty days does not count last quarter's traffic."""
    async def seed(session):
        old, recent = _person(session), _person(session)
        await session.flush()
        await _walk(session, old, "landing_view")
        await _walk(session, recent, "landing_view")
        long_ago = utcnow() - timedelta(days=90)
        for row in (
            await session.execute(select(Event).where(Event.user_id == old.id))
        ).scalars():
            row.created_at = long_ago
        await session.flush()
        return await funnel.funnel(session, since=utcnow() - timedelta(days=30))

    assert _steps(_run(db, seed))["landing_view"].reached == 1


def test_an_empty_stage_reports_no_rate_rather_than_nought_percent(db):
    """Nobody arrived is a different sentence from nobody converted."""
    steps = _steps(_run(db, lambda session: funnel.funnel(session)))
    assert steps["landing_view"].reached == 0
    assert steps["quiz_start"].rate is None


def test_forgetting_an_account_takes_its_events_with_it(db):
    """Deletion is real, and this table holds rows that are somebody's."""
    async def seed(session):
        mine, theirs = _person(session), _person(session)
        await session.flush()
        await _walk(session, mine, "landing_view", "quiz_start")
        await _walk(session, theirs, "landing_view")
        gone = await funnel.forget(session, mine.id)
        left = await funnel.funnel(session)
        return gone, left

    gone, left = _run(db, seed)
    assert gone == 2
    assert _steps(left)["landing_view"].reached == 1


def test_forgetting_reaches_back_to_before_the_account_existed(db):
    """The rows from the journey are theirs, and they do not carry the account id.

    Somebody who walked the whole journey and then saved a birth has their
    landing view filed under a browser id. Erasing only the rows that name the
    account would leave those behind — still joined to each other, still joined
    to a string that is still in that person's browser — while the privacy page
    says the step labels went with everything else. Somebody else's rows, under
    an id this account never claimed, must not go with them.
    """
    async def seed(session):
        mine, theirs = _person(session), _person(session)
        await session.flush()

        await funnel.record(session, user_id=None, anon_id="my-browser", stage="landing_view")
        await funnel.record(session, user_id=None, anon_id="my-browser", stage="quiz_start")
        await funnel.claim(session, anon_id="my-browser", user_id=mine.id)
        await _walk(session, mine, "quiz_complete")

        await funnel.record(
            session, user_id=None, anon_id="their-browser", stage="landing_view"
        )
        await _walk(session, theirs, "landing_view")

        gone = await funnel.forget(session, mine.id)
        left = (await session.execute(select(Event))).scalars().all()
        claims = (await session.execute(select(AnonymousVisitor))).scalars().all()
        return gone, {(row.user_id, row.anon_id) for row in left}, len(claims), theirs.id

    gone, left, claims, other = _run(db, seed)
    # Two from before the account and one from after it.
    assert gone == 3
    # Both of somebody else's, under both kinds of identity, untouched.
    assert left == {(None, "their-browser"), (other, None)}
    assert claims == 0


def test_nothing_outlives_the_retention_the_privacy_page_states(db):
    """A promise about deletion is worth what the code behind it does.

    Every row past the cutoff, not only the anonymous ones: deleting the
    unattributed top of an old funnel while leaving the purchases below it would
    leave a dataset that is not smaller but wrong, with every historical rate
    divided by a denominator that had been quietly shrunk.
    """
    async def seed(session):
        person = _person(session)
        await session.flush()
        await funnel.record(session, user_id=None, anon_id="old-browser", stage="landing_view")
        await funnel.claim(session, anon_id="old-browser", user_id=person.id)
        await _walk(session, person, "quiz_start")
        await funnel.record(session, user_id=None, anon_id="new-browser", stage="landing_view")

        long_ago = utcnow() - timedelta(days=funnel.PURGE_AFTER_DAYS + 1)
        for row in (
            await session.execute(
                select(Event).where(
                    (Event.anon_id == "old-browser") | (Event.user_id == person.id)
                )
            )
        ).scalars():
            row.created_at = long_ago
        for row in (await session.execute(select(AnonymousVisitor))).scalars():
            row.claimed_at = long_ago
        await session.flush()

        gone = await funnel.purge(session)
        left = (await session.execute(select(Event))).scalars().all()
        claims = (await session.execute(select(AnonymousVisitor))).scalars().all()
        return gone, [row.anon_id for row in left], claims

    gone, left, claims = _run(db, seed)
    assert gone == 2
    assert left == ["new-browser"]
    # The join goes with the rows it joined. It is an identifier of somebody's
    # too, and one kept after everything it pointed at is gone is a record of a
    # browser and an account and nothing else.
    assert claims == []


def test_a_claim_still_being_used_survives_the_cutoff(db):
    """An old claim whose browser came back yesterday is not dead weight.

    Deleting it on its own age would split one person in two at exactly the
    moment they returned, which is the failure this table exists to prevent —
    arriving through housekeeping instead of through a missing header.
    """
    async def seed(session):
        person = _person(session)
        await session.flush()
        await funnel.record(session, user_id=None, anon_id="old-browser", stage="landing_view")
        await funnel.claim(session, anon_id="old-browser", user_id=person.id)
        for row in (await session.execute(select(AnonymousVisitor))).scalars():
            row.claimed_at = utcnow() - timedelta(days=funnel.PURGE_AFTER_DAYS + 1)
        await session.flush()

        await funnel.purge(session)
        return (await session.execute(select(AnonymousVisitor))).scalars().all()

    assert len(_run(db, seed)) == 1


def test_record_refuses_a_stage_the_endpoint_would_have_refused(db):
    """The rule lives in the module, not in the route that happens to call it.

    Server-side callers — the webhook, the checkout route — go straight to
    `record`, and a rule enforced only at the HTTP edge is a rule that does not
    apply to them.
    """
    async def attempt(session):
        person = _person(session)
        await session.flush()
        with pytest.raises(funnel.UnknownStage):
            await funnel.record(session, user_id=person.id, stage="signup_completed")

    _run(db, attempt)


def test_record_refuses_a_ladder_event_with_no_surface_on_it(db):
    """Гейт §А12 держится в модуле, а не на маршруте.

    Серверный вызов — вебхук, задача рассылки, код, написанный через полгода —
    приходит в `record` мимо HTTP. Правило, живущее только на краю, для них не
    существует, и событие лестницы без поверхности они записали бы молча.
    """
    async def attempt(session):
        person = _person(session)
        await session.flush()

        with pytest.raises(funnel.SurfaceMissing):
            await funnel.record(session, user_id=person.id, stage="paywall_shown")

        with pytest.raises(funnel.UnknownSurface):
            await funnel.record(
                session,
                user_id=person.id,
                stage="paywall_shown",
                properties={"surface": "checkout"},
            )

        return (await session.execute(select(Event))).scalars().all()

    assert _run(db, attempt) == []


def test_the_ladder_answers_the_number_the_brief_asks_of_it(db):
    """«Save-оффер спасает ≥10% отмен» — это строка отчёта, а не оценка.

    Ради неё у ступеней лестницы и расставлен `after`: четверо вошли в отмену,
    троим показали спасательный оффер, один его принял. Набор мал настолько,
    что ответ читается рукой, — единственный способ знать, что запрос считает
    то, что обещает.
    """
    async def seed(session):
        everyone = [_person(session) for _ in range(4)]
        await session.flush()
        a, b, c, d = everyone
        await _walk(session, a, "cancel_flow_entered", "save_offer_shown",
                    "save_offer_accepted", surface="p8")
        await _walk(session, b, "cancel_flow_entered", "save_offer_shown", surface="p8")
        await _walk(session, c, "cancel_flow_entered", "save_offer_shown", surface="p8")
        await _walk(session, d, "cancel_flow_entered", surface="p8")
        return await funnel.funnel(session)

    steps = _steps(_run(db, seed))
    assert steps["cancel_flow_entered"].reached == 4
    assert steps["save_offer_shown"].reached == 3
    assert steps["save_offer_shown"].rate == 0.75
    assert steps["save_offer_accepted"].reached == 1
    assert steps["save_offer_accepted"].rate == pytest.approx(1 / 3)


def test_a_paywall_that_was_shown_and_one_that_was_paid_for_are_not_chained(db):
    """Закрытие пейволла и переход в оплату — братья, а не шаги.

    Сцепив их в цепочку, `paywall_dismissed` считал бы закрывших **среди**
    дошедших до оплаты: ноль, неотличимый от сломанного маяка. Здесь один
    человек закрыл, другой пошёл платить, и обе доли считаются от показа.
    """
    async def seed(session):
        shown_only, dismissed, checked_out = (_person(session) for _ in range(3))
        await session.flush()
        await _walk(session, shown_only, "paywall_shown", surface="p5")
        await _walk(session, dismissed, "paywall_shown", "paywall_dismissed", surface="p5")
        await _walk(session, checked_out, "paywall_shown", "checkout_started", surface="p5")
        return await funnel.funnel(session)

    steps = _steps(_run(db, seed))
    assert steps["paywall_shown"].reached == 3
    assert steps["paywall_dismissed"].reached == 1
    assert steps["checkout_started"].reached == 1
    assert steps["paywall_dismissed"].of == "paywall_shown"
    assert steps["checkout_started"].of == "paywall_shown"


def test_deleting_an_account_reaches_the_journey_that_happened_before_the_merge(db):
    """The claim can be filed under a row the person no longer uses.

    Guest on a phone, then a sign-in to an account they already had. The browser
    id was claimed by the *guest*, because that was the row that existed when the
    browser handed it over; `accounts.merge` folds the guest in and moves the
    events that carry a user id, but the ones from before the account existed
    carry none and stay where they are. Deleting the surviving account has to
    reach them anyway — otherwise the erasure looks complete and leaves the whole
    first half of somebody's journey behind, still tied to a string still sitting
    in their browser.
    """
    async def seed(session):
        guest, existing = _person(session), _person(session)
        await session.flush()

        await funnel.record(session, user_id=None, anon_id="phone-browser", stage="landing_view")
        await funnel.claim(session, anon_id="phone-browser", user_id=guest.id)
        guest.merged_into_id = existing.id
        await _walk(session, existing, "quiz_start")
        await session.flush()

        gone = await funnel.forget(session, existing.id)
        left = (await session.execute(select(Event))).scalars().all()
        claims = (await session.execute(select(AnonymousVisitor))).scalars().all()
        return gone, left, claims

    gone, left, claims = _run(db, seed)
    assert gone == 2
    assert left == []
    assert claims == []
