"""A database that already exists has to keep working.

`create_all` creates missing tables and never touches one that is already
there, so every column added to a model since the last deploy is a column the
live database does not have — and the failure is a 500 on the first `SELECT`,
which here means the paywall, the hub, `/v1/account` and the billing webhook
at once. The suite could not see it, because every test database is built from
nothing.

These tests build the *old* shape on purpose and then assert that a boot
brings it forward. That is the only way to test a migration: against a
database that predates it.
"""

from __future__ import annotations

import asyncio

import pytest
from conftest import database_url, postgres_url, run_async
from sqlalchemy import select, text

from alma.db.migrate import SchemaTooOld, reconcile
from alma.db.models import Entitlement, Purchase


def _ddl(statement: str) -> str:
    """The same yesterday-shaped table, spelled for the database in use.

    The DDL below is written by hand precisely because the models no longer
    know how to declare it, which means it also cannot borrow SQLAlchemy's
    dialect rendering. Two spellings differ and both are load-bearing:
    `AUTOINCREMENT` is SQLite's and Postgres has identity columns instead, and
    `DATETIME` is a SQLite affinity that Postgres has never heard of — a
    migration test that ran only against SQLite would prove the migration on
    the one database this product does not deploy.
    """
    if postgres_url() is None:
        return statement
    return statement.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    ).replace("DATETIME", "TIMESTAMP WITH TIME ZONE")


@pytest.fixture
def old_database(tmp_path, monkeypatch):
    """A database with yesterday's `entitlement` and `purchase` tables.

    Written as raw DDL rather than by trimming the models, because the point
    is a schema this code no longer knows how to declare.
    """
    from alma import config as config_module
    from alma.db import session as session_module

    asyncio.run(session_module.dispose())
    monkeypatch.setenv("ALMA_DATABASE_URL", database_url(tmp_path, "old.db"))
    monkeypatch.setenv("ALMA_JWT_SECRET", "test-secret-not-the-default")
    config_module.settings.cache_clear()

    async def build() -> None:
        async with session_module.engine().begin() as connection:
            await connection.execute(text(_ddl("""
                CREATE TABLE entitlement (
                    id VARCHAR(32) PRIMARY KEY,
                    user_id VARCHAR(32) NOT NULL,
                    system VARCHAR(32) NOT NULL,
                    kind VARCHAR(16) NOT NULL,
                    granted_at DATETIME NOT NULL,
                    expires_at DATETIME,
                    revoked_at DATETIME,
                    source VARCHAR(32) NOT NULL,
                    transaction_id VARCHAR(64),
                    amount_cents INTEGER NOT NULL,
                    currency VARCHAR(3) NOT NULL
                )
            """)))
            await connection.execute(text(_ddl("""
                CREATE TABLE purchase (
                    id VARCHAR(32) PRIMARY KEY,
                    user_id VARCHAR(32),
                    provider VARCHAR(16) NOT NULL,
                    transaction_id VARCHAR(64) NOT NULL UNIQUE,
                    checkout_id VARCHAR(64),
                    price_id VARCHAR(64),
                    product VARCHAR(64),
                    status VARCHAR(24) NOT NULL,
                    amount_cents INTEGER NOT NULL,
                    currency VARCHAR(3) NOT NULL,
                    country VARCHAR(2),
                    created_at DATETIME NOT NULL,
                    completed_at DATETIME,
                    refunded_at DATETIME,
                    payload JSON NOT NULL
                )
            """)))
            await connection.execute(text(
                "INSERT INTO entitlement VALUES ('e1', 'u1', 'natal', 'one_time', "
                "'2026-01-01 00:00:00', NULL, NULL, 'paddle', 'txn_old', 899, 'USD')"
            ))
            await connection.execute(text(
                "INSERT INTO purchase VALUES ('p1', 'u1', 'paddle', 'txn_old', NULL, "
                "NULL, 'natal', 'transaction.completed', 899, 'USD', 'IT', "
                "'2026-01-01 00:00:00', '2026-01-01 00:00:00', NULL, '{}')"
            ))

    run_async(build)
    yield session_module
    asyncio.run(session_module.dispose())
    config_module.settings.cache_clear()


def test_the_old_shape_is_unqueryable_until_it_is_brought_forward(old_database):
    """The failure this exists to prevent, reproduced before it is fixed.

    `DatabaseError` rather than `OperationalError`: SQLite reports an unknown
    column as operational and Postgres reports it as programming, and the
    assertion that matters is the column name in the message, not which of
    SQLAlchemy's two wrappers carried it.
    """
    from sqlalchemy.exc import DatabaseError

    async def work():
        async with old_database.session_factory()() as session:
            await session.execute(select(Entitlement).limit(1))

    with pytest.raises(DatabaseError, match="subscription_id"):
        run_async(work)


def test_a_boot_brings_an_existing_database_forward(old_database):
    """`create_all` alone does not, which is the whole point."""
    async def work():
        await old_database.create_all()
        async with old_database.session_factory()() as session:
            held = (await session.execute(select(Entitlement))).scalars().all()
            paid = (await session.execute(select(Purchase))).scalars().all()
            return held, paid

    held, paid = run_async(work)
    assert [e.system for e in held] == ["natal"]
    assert held[0].subscription_id is None
    assert held[0].renews_at is None
    assert [p.transaction_id for p in paid] == ["txn_old"]


def test_a_row_written_before_scope_existed_is_backfilled_not_left_null(old_database):
    """`covers()` reads `scope` first now, so a NULL there is not "no opinion".

    It would fall through to the legacy shape by accident rather than by rule,
    and the next branch added above the fall-through would silently change
    what every pre-existing purchase means. The column carries a server
    default so the database fills it in, not just this process.
    """
    async def work():
        await old_database.create_all()
        async with old_database.session_factory()() as session:
            row = (await session.execute(select(Entitlement))).scalars().one()
            return row.scope, row.covers("natal"), row.covers("transits")

    scope, own, other = run_async(work)
    assert scope == "system"
    assert own is True and other is False


def test_running_it_twice_changes_nothing(old_database):
    """It runs on every boot, so the second boot has to be a no-op."""
    async def work():
        await old_database.create_all()
        return await reconcile()

    assert run_async(work) == []


def test_a_change_it_cannot_make_is_refused_rather_than_skipped():
    """A migration that silently declines half its work is the original bug.

    A NOT NULL column with no server default has nothing to put in the rows
    that already exist — SQLite refuses outright and Postgres has to be told —
    so it is a change that needs a person. `default=` on the mapping is not
    enough: SQLAlchemy applies that at INSERT and the database has never heard
    of it, which is exactly the trap `scope` would have fallen into.
    """
    from sqlalchemy import Column, Integer, MetaData, String, Table
    from sqlalchemy.dialects import sqlite

    from alma.db.migrate import _add_column_sql

    class _Connection:
        dialect = sqlite.dialect()

    table = Table(
        "example",
        MetaData(),
        Column("nullable_one", String(8)),
        Column("defaulted", Integer, nullable=False, server_default="0"),
        Column("python_default_only", String(8), nullable=False, default="x"),
    )
    connection = _Connection()

    assert _add_column_sql(connection, table, table.c.nullable_one).endswith("VARCHAR(8)")
    assert _add_column_sql(connection, table, table.c.defaulted).endswith("DEFAULT 0")
    with pytest.raises(SchemaTooOld, match="python_default_only"):
        _add_column_sql(connection, table, table.c.python_default_only)


def test_a_column_no_model_declares_is_named_and_its_rows_are_left_alone(
    old_database, caplog
):
    """The half of a rename this module cannot see, and must not act on.

    A renamed column reaches here as two facts that look identical to a fresh
    column and an old one: the new name is added empty, the old name keeps every
    row. Dropping the old one would be the module doing exactly what its
    docstring forbids, and staying silent about it was the real gap — the boot
    log said the migration succeeded, and it had done half the work.

    Both halves are asserted, and the data one is the one that matters: the
    value has to still be there afterwards.
    """
    import logging

    async def work():
        async with old_database.engine().begin() as connection:
            await connection.execute(
                text("ALTER TABLE purchase ADD COLUMN buyer_note VARCHAR(64)")
            )
            await connection.execute(
                text("UPDATE purchase SET buyer_note = 'do not lose me'")
            )
        await old_database.create_all()
        async with old_database.session_factory()() as session:
            kept = await session.execute(text("SELECT buyer_note FROM purchase"))
            return kept.scalar_one()

    with caplog.at_level(logging.WARNING, logger="alma.db.migrate"):
        assert run_async(work) == "do not lose me"

    assert any(
        "purchase.buyer_note" in record.getMessage() for record in caplog.records
    ), "a column the models do not know about has to be named at boot, once"


@pytest.fixture
def database_without_the_anonymous_funnel(tmp_path, monkeypatch):
    """A database whose `event` table predates anybody being measured anonymously.

    This is the shape of the live one: rows attributed to accounts, because
    every visitor was given an account whether they wanted one or not. Two
    changes have to land on it — a column on a table that already exists, and a
    whole table that does not — and the two travel by different paths through
    boot, so a test that only proved one of them would pass on a database where
    the funnel silently stopped joining.
    """
    from alma import config as config_module
    from alma.db import session as session_module

    asyncio.run(session_module.dispose())
    monkeypatch.setenv("ALMA_DATABASE_URL", database_url(tmp_path, "funnel-old.db"))
    monkeypatch.setenv("ALMA_JWT_SECRET", "test-secret-not-the-default")
    config_module.settings.cache_clear()

    async def build() -> None:
        async with session_module.engine().begin() as connection:
            await connection.execute(text(_ddl("""
                CREATE TABLE event (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id VARCHAR(32),
                    name VARCHAR(64) NOT NULL,
                    properties JSON NOT NULL,
                    created_at DATETIME NOT NULL
                )
            """)))
            await connection.execute(text(
                "INSERT INTO event (user_id, name, properties, created_at) "
                "VALUES ('u1', 'landing_view', '{}', '2026-01-01 00:00:00')"
            ))

    run_async(build)
    yield session_module
    asyncio.run(session_module.dispose())
    config_module.settings.cache_clear()


def test_a_boot_gives_the_old_funnel_both_halves_of_the_join(
    database_without_the_anonymous_funnel,
):
    """The column arrives by ALTER and the table by create_all, and both must.

    Without the column the beacon writes nothing at all, which is loud. Without
    the *table* the beacon keeps working and the account is still minted — only
    the claim silently fails, so the stages before an account and the stages
    after it never fold together and the first conversion rate reads zero on a
    database that looks perfectly healthy. That is the quieter of the two
    failures and the reason this asserts on both.
    """
    from alma.db.models import AnonymousVisitor, Event

    db = database_without_the_anonymous_funnel

    async def work():
        await db.create_all()
        async with db.session_factory()() as session:
            old = (await session.execute(select(Event))).scalars().one()
            # A write of the new shape has to land on the migrated table, not
            # merely be declarable against the model.
            session.add(Event(anon_id="a-browser-with-no-account", name="landing_view",
                              properties={}))
            session.add(AnonymousVisitor(anon_id="a-browser-with-no-account", user_id="u1"))
            await session.flush()
            rows = (await session.execute(select(Event))).scalars().all()
            claims = (await session.execute(select(AnonymousVisitor))).scalars().all()
            return old.anon_id, [r.anon_id for r in rows], [c.user_id for c in claims]

    before, after, claims = run_async(work)
    # The rows that predate the column read as "no browser id", which is the
    # truth about them: they were written by people who had already been given
    # an account for looking at a page.
    assert before is None
    assert sorted(a or "" for a in after) == ["", "a-browser-with-no-account"]
    assert claims == ["u1"]


@pytest.fixture
def thread_without_a_source(tmp_path, monkeypatch):
    """База с `chat_message` вчерашней формы — без `source_chapter`.

    Отдельная фикстура, а не ещё две колонки в `old_database`: та описывает
    конкретный случай из прошлого (`entitlement` и `purchase`), и дописывать в
    неё каждую новую колонку значит превращать сценарий в свалку. Здесь важно
    ровно одно — беседа, написанная до колонки, читается после неё.
    """
    from alma import config as config_module
    from alma.db import session as session_module

    asyncio.run(session_module.dispose())
    monkeypatch.setenv("ALMA_DATABASE_URL", database_url(tmp_path, "threads.db"))
    monkeypatch.setenv("ALMA_JWT_SECRET", "test-secret-not-the-default")
    config_module.settings.cache_clear()

    async def build() -> None:
        async with session_module.engine().begin() as connection:
            # Без FK на `chat_thread`: строится одна таблица, и внешний ключ на
            # несуществующую соседку Postgres не примет, а проверяется здесь не он.
            await connection.execute(text(_ddl("""
                CREATE TABLE chat_message (
                    id VARCHAR(32) PRIMARY KEY,
                    thread_id VARCHAR(32) NOT NULL,
                    role VARCHAR(12) NOT NULL,
                    body TEXT NOT NULL,
                    cited_factors JSON NOT NULL,
                    turn_kind VARCHAR(16),
                    model VARCHAR(64),
                    cost_cents FLOAT NOT NULL,
                    created_at DATETIME NOT NULL
                )
            """)))
            await connection.execute(text(
                "INSERT INTO chat_message VALUES ('m1', 't1', 'alma', 'Said before "
                "the column existed.', '[]', 'reading', 'haiku', 0.4, "
                "'2026-01-01 00:00:00')"
            ))

    run_async(build)
    yield session_module
    asyncio.run(session_module.dispose())
    config_module.settings.cache_clear()


def test_a_conversation_written_before_the_column_still_reads(thread_without_a_source):
    """Колонка добавляется сама, а старая реплика честно отвечает «главы нет».

    Самодельный механизм не регистрируют — он читает желаемую схему прямо из
    `Base.metadata`, поэтому весь вклад этой колонки в миграцию — то, что она
    объявлена nullable. Проверяется именно это: боот доводит базу, а строка,
    написанная до колонки, читается с null, а не падает и не выдумывает главу.
    """
    from alma.db.models import ChatMessage

    async def bring_forward() -> list[str]:
        return await reconcile()

    applied = run_async(bring_forward)
    assert any("source_chapter" in statement for statement in applied), applied

    async def read() -> ChatMessage:
        async with thread_without_a_source.session_scope() as session:
            rows = (await session.execute(select(ChatMessage))).scalars().all()
            return rows[0]

    row = run_async(read)
    assert row.source_chapter is None
