import Foundation

/// Every string the daily shows, named.
///
/// A sixth String Catalog, for the reason `ScreenL10n` gives about the fifth: a
/// catalog is one JSON document with one `strings` object, so a table per owner
/// is what makes two agents editing at once safe, and `LocalizedStringResource`
/// takes a table name, so the cost is one argument paid here and at no call site.
///
/// **The push keys are deliberately not here.** `push.daily.square` and its ten
/// siblings live in `Localizable.xcstrings`, because `loc-key` in an APNs
/// payload is resolved by iOS itself and iOS looks it up in `Localizable.strings`
/// and nowhere else — there is no table parameter in a notification payload. A
/// push key filed in this table would arrive on a lock screen as the raw key.
/// `PushPayload` names them as plain strings for that reason; nothing in Swift
/// ever resolves them.
///
/// Generated by `tools/gen_daily_strings.py`, which also merges the push keys
/// into the shell's catalog. Add a key there, not by hand in the JSON, which is
/// where a missing language hides.
enum DailyL10n {

    static let table = "Daily"

    // MARK: — the setting

    static let settingTitle = LocalizedStringResource("daily.setting.title", defaultValue: "The daily", table: table)

    static let off = LocalizedStringResource("daily.setting.off", defaultValue: "Off", table: table)
    static let occasionally = LocalizedStringResource("daily.setting.occasionally", defaultValue: "Occasionally", table: table)
    static let onlyWhatMatters = LocalizedStringResource("daily.setting.onlyWhatMatters", defaultValue: "Only what matters", table: table)

    static let offDetail = LocalizedStringResource("daily.setting.off.detail", defaultValue: "No notifications. Today is still here whenever you open it.", table: table)
    static let occasionallyDetail = LocalizedStringResource("daily.setting.occasionally.detail", defaultValue: "About once a week, when something in your chart is actually exact.", table: table)
    static let onlyMattersDetail = LocalizedStringResource("daily.setting.onlyMatters.detail", defaultValue: "A few times a year. The slow ones only — the transits that last months.", table: table)

    static let hour = LocalizedStringResource("daily.setting.hour", defaultValue: "Arrives at", table: table)
    static let quiet = LocalizedStringResource("daily.setting.quiet", defaultValue: "Never between 22:00 and 08:00, in your time.", table: table)

    static let timezone = LocalizedStringResource("daily.setting.timezone", defaultValue: "Your time", table: table)
    static let timezoneFromDevice = LocalizedStringResource("daily.setting.timezone.device", defaultValue: "from your device", table: table)
    static let timezoneFromBirth = LocalizedStringResource("daily.setting.timezone.birth", defaultValue: "from your birth data", table: table)
    static let timezoneChosen = LocalizedStringResource("daily.setting.timezone.chosen", defaultValue: "you chose this", table: table)

    // MARK: — the actions on the notification itself

    static let turnOff = LocalizedStringResource("daily.action.turnOff", defaultValue: "Turn these off", table: table)
    static let quieter = LocalizedStringResource("daily.action.quieter", defaultValue: "Fewer of these", table: table)
    static let turnedOff = LocalizedStringResource("daily.action.turnedOff", defaultValue: "Turned off. Today is still here whenever you open it.", table: table)

    // MARK: — the block on Today

    static let todayLabel = LocalizedStringResource("daily.today.label", defaultValue: "Exact today", table: table)
    static let emptyTitle = LocalizedStringResource("daily.empty.title", defaultValue: "Nothing is exact today", table: table)
    static let emptyBody = LocalizedStringResource("daily.empty.body", defaultValue: "What is still in orb is below. Nothing perfects today.", table: table)

    static func exactAt(_ time: String) -> LocalizedStringResource {
        LocalizedStringResource("daily.today.at", defaultValue: "Exact at \(time)", table: table)
    }

    static func inOrbSince(_ date: String) -> LocalizedStringResource {
        LocalizedStringResource("daily.today.since", defaultValue: "In orb since \(date)", table: table)
    }

    static func inOrbUntil(_ date: String) -> LocalizedStringResource {
        LocalizedStringResource("daily.today.until", defaultValue: "in orb until \(date)", table: table)
    }

    // MARK: — the ask

    /// The aspect, in words, for `DailyContact.notation`. Runtime-keyed for the
    /// same reason as the sign names: the key is the engine's aspect name and
    /// only exists at run time.
    static func aspectWord(_ aspect: String) -> String {
        let key = "daily.aspect.\(aspect)"
        let found = String(localized: String.LocalizationValue(key), table: table, bundle: .main)
        return found == key ? aspect : found
    }

    static var retrogradeWord: String {
        String(localized: "daily.retrograde", defaultValue: "retrograde", table: table)
    }

    static var yourWord: String {
        String(localized: "daily.your", defaultValue: "your", table: table)
    }

    /// How one contact is said, per language. See `DailyContact.notation` for
    /// why this is a template rather than four pieces glued together.
    ///
    /// `%1$@` transiting body · `%2$@` aspect · `%3$@` natal body.
    static let contactPhrase = LocalizedStringResource(
        "daily.contactPhrase", defaultValue: "%1$@ %2$@ your %3$@", table: table
    )

    /// What the block says on a day with nothing exact **and** something live.
    ///
    /// The old pair — "Nothing is exact today / What is still in orb is below"
    /// — was accurate and read as an empty product: the first thing on the
    /// front page was a sentence about absence, and the owner's reaction was to
    /// ask whether the content was behind the subscription. It is not; most
    /// days simply have no exact aspect, which is the very fact that makes an
    /// exact one worth a notification.
    ///
    /// So the headline still refuses to invent an event, and the line under it
    /// carries a number instead of a shrug.
    static let runningTitle = LocalizedStringResource("daily.running.title", defaultValue: "Nothing perfects today", table: table)

    /// The quiet day, when we know when the nearest contact perfects.
    ///
    /// **This replaced a count.** The line used to read «38 влияний медленно
    /// движутся; сильнейшие ниже» and the owner did not know what it meant —
    /// fairly, because thirty-eight of anything is not a fact about a person,
    /// it is a number from our own arithmetic. Naming the one contact that is
    /// closest, and the day it is exact, is the same sentence made checkable.
    ///
    /// The wording avoids agreeing with the aspect's gender in Russian — a
    /// «квадрат» is masculine and an «оппозиция» is feminine, and «точен» after
    /// either one is a coin flip. A colon has no gender.
    static func runningNearest(_ contact: String, _ date: String) -> LocalizedStringResource {
        LocalizedStringResource("daily.running.nearest", defaultValue: "The closest is \(contact), exact on \(date). Everything else is moving slowly.", table: table)
    }

    static func runningBody(_ contact: String) -> LocalizedStringResource {
        LocalizedStringResource("daily.running.body", defaultValue: "The closest is \(contact). Everything else is moving slowly.", table: table)
    }

    static let askTitle = LocalizedStringResource("daily.ask.title", defaultValue: "Tell me the morning it happens", table: table)
    static let askBody = LocalizedStringResource("daily.ask.body", defaultValue: "One notification, at 08:00, on the days something in your chart is exact. About once a week. Never at night, and you can turn it off from inside the notification itself.", table: table)
    static let askYes = LocalizedStringResource("daily.ask.yes", defaultValue: "Yes, tell me", table: table)
    static let askNo = LocalizedStringResource("daily.ask.no", defaultValue: "Not now", table: table)

    // MARK: — the status, which has to be true

    static let denied = LocalizedStringResource("daily.status.denied", defaultValue: "Notifications are off for Alma. You can turn them on in your phone's settings.", table: table)
    static let openSettings = LocalizedStringResource("daily.status.openSettings", defaultValue: "Open settings", table: table)
    static let provisional = LocalizedStringResource("daily.status.provisional", defaultValue: "Arriving quietly. Alma's notifications go straight to Notification Center — no banner, no sound — until you decide otherwise.", table: table)
    static let upgrade = LocalizedStringResource("daily.status.upgrade", defaultValue: "Let them arrive properly", table: table)
    static let notDelivering = LocalizedStringResource("daily.status.notDelivering", defaultValue: "Nothing is being sent yet. This phone is not registered for notifications, so the daily lives here, on Today.", table: table)
    static let registered = LocalizedStringResource("daily.status.registered", defaultValue: "This phone is registered for the daily.", table: table)

    static let subscriberOnly = LocalizedStringResource("daily.subscriberOnly", defaultValue: "The daily is part of the monthly plan. Today is free, and always will be.", table: table)

    // MARK: — the claim, checked

    static let verifiedLabel = LocalizedStringResource("daily.verified.label", defaultValue: "Exact days in the next 30", table: table)
    static let verifiedNote = LocalizedStringResource("daily.verified.note", defaultValue: "Counted from your own chart, on this device, with the same rule the notification uses.", table: table)
}
