import Foundation

/// Every string the paywall shows, named — the same discipline as `L10n`, in a
/// table of its own.
///
/// **Why a second String Catalog rather than more keys in `Localizable`.** Three
/// agents are adding screens to this project at the same time, and
/// `Localizable.xcstrings` is one JSON document: two of them appending keys to it
/// is the one merge conflict a file-system synchronized folder group cannot
/// prevent. A separate table is a separate file, it compiles to its own
/// `Paywall.strings` inside each `.lproj`, and `LocalizedStringResource` resolves
/// it by name — so the isolation costs one `table:` argument and buys a file
/// nobody else writes to. If the two are ever merged, every constant below moves
/// and no call site changes.
///
/// **The wording is not invented here where it already existed.** Most of these
/// are lifted from `src/lib/i18n/`, so the app and the web say the same sentence
/// in the same voice; the comment on each catalogue entry names the key it came
/// from. Three of them were deliberately *changed* rather than copied, and that
/// is the interesting part:
///
/// * `pricing.renewsNote` promises cancelling is "two taps, from Settings". On
///   iOS it is not: Apple owns the subscription and the cancel control lives in
///   the Apple ID settings. Shipping the web sentence would be a false statement
///   about a recurring charge, on the screen where the charge is agreed to.
/// * `pricing.honesty[1]` promises an email before every renewal. That email is
///   sent by our own webhook when *we* are the merchant. Apple is the merchant
///   here and the renewal notice is Apple's.
/// * `pricing.honesty[2]` says the same thing as `renewsNote` and gets the same
///   correction.
///
/// Everything is regenerated by `tools/gen_paywall_strings.py`, which is where a
/// new key goes: the six languages sit next to each other there, and the script
/// refuses to write a key that is missing one.
enum PaywallL10n {

    // MARK: — the frame

    static let label = res("paywall.label", "what it costs")
    static let doorSub = res(
        "paywall.doorSub",
        "The numbers above are yours and stay free. This opens the whole system — every chapter of the reading, written from your positions, not a template."
    )
    static let everythingTitle = res("paywall.everythingTitle", "Open the rest of what your chart says")
    static let everythingSub = res(
        "paywall.everythingSub",
        "Written from your own positions the first time you open it — your chart, never a template."
    )
    /// The annual's arithmetic, under its billed price. Positional arguments
    /// because German and French move the percent around the words.
    static func perMonthSavings(_ perMonth: String, _ percent: Int) -> LocalizedStringResource {
        LocalizedStringResource(
            "paywall.perMonthSavings",
            defaultValue: "\(perMonth) a month · save \(percent)%",
            table: "Paywall")
    }

    static let pitchDoor1 = res("paywall.pitchDoor1", "One payment opens every chapter of this system.")
    static let pitchDoor2 = res(
        "paywall.pitchDoor2",
        "Each chapter is written from your own positions the first time you open it.")
    static let pitchDoor3 = res("paywall.pitchDoor3", "Yours permanently — read it any time, in six languages.")
    static let pitchPlan1 = res("paywall.pitchPlan1", "All eight systems stay open while the plan runs.")
    static let pitchPlan2 = res(
        "paywall.pitchPlan2",
        "Transits, the solar return and compatibility are rewritten as the sky moves.")
    static let pitchPlan3 = res("paywall.pitchPlan3", "Thirty questions a month to Alma, on the deeper voice.")

    static let freeNote = res(
        "paywall.freeNote",
        "Every calculation stays free, always. What has a price is the writing."
    )

    // MARK: — the rungs

    static let doorNote = res("paywall.doorNote", "One payment. Yours permanently.")
    static let archiveTitle = res("paywall.archiveTitle", "The whole archive")
    static let archiveNote = res("paywall.archiveNote", "All eight systems, bought once.")
    static let upgradeTitle = res("paywall.upgradeTitle", "The rest of the archive")
    static let upgradeNote = res(
        "paywall.upgradeNote", "The archive, less what you already paid for one system."
    )
    static let weeklyTitle = res("paywall.weeklyTitle", "Everything live, weekly")
    static let weeklyNote = res(
        "paywall.weeklyNote",
        "Try the living layer for one week. Renews weekly until you cancel."
    )
    static let monthlyTitle = res("paywall.monthlyTitle", "Everything live, monthly")
    static let monthlyNote = res(
        "paywall.monthlyNote",
        "Transits, the solar return and compatibility while they move, plus 30 questions a month. Renews until you cancel."
    )
    static let annualTitle = res("paywall.annualTitle", "Everything, for a year")
    static let annualNote = res(
        "paywall.annualNote",
        "Renews every year until you cancel. Cancel any time in your Apple ID settings."
    )

    // MARK: — the eight, as row titles

    /// The system names, ours rather than the store's.
    ///
    /// **This is deliberately not `Product.displayName`,** which would be the
    /// obvious choice and is wrong. App Store Connect localises product metadata
    /// per *storefront*, not per device language: a German speaker with a US
    /// Apple ID sees the US storefront, so `displayName` would put "Natal chart"
    /// in the middle of a German paywall. The price has to come from StoreKit
    /// because that is the money; the name has to come from here because that is
    /// the language.
    static func systemName(_ system: SystemSlug) -> LocalizedStringResource {
        switch system {
        case .natal: res("paywall.system.natal", "Natal chart")
        case .numerology: res("paywall.system.numerology", "Numerology")
        case .birthCard: res("paywall.system.birthCard", "Birth Card")
        case .transits: res("paywall.system.transits", "Transits")
        case .solarReturn: res("paywall.system.solarReturn", "Solar return")
        case .compatibility: res("paywall.system.compatibility", "Compatibility")
        case .astrocartography: res("paywall.system.astrocartography", "Astrocartography")
        case .synthesis: res("paywall.system.synthesis", "Cross-synthesis")
        }
    }

    // MARK: — controls

    static let notNow = res("paywall.notNow", "Not now")
    static let skip = res("paywall.skip", "Not now — take me in")
    static let oneTimeFine = res(
        "paywall.oneTimeFine", "One payment. Yours permanently. No account needed to buy."
    )
    static let restore = res("paywall.restore", "Restore purchases")
    static let restoring = res("paywall.restoring", "Asking the App Store…")

    // MARK: — outcomes

    static let restoredNone = res(
        "paywall.restoredNone", "The App Store has nothing to restore for this Apple ID."
    )
    static let restoredOther = res(
        "paywall.restoredOther",
        "These purchases already belong to another Alma account. Sign in with that one and they come with you."
    )
    static let restored = res("paywall.restored", "Restored. Everything you bought is open again.")
    static let pending = res(
        "paywall.pending",
        "Waiting for approval. Nothing has been charged, and this opens by itself the moment it is approved."
    )
    static let storeUnavailable = res(
        "paywall.storeUnavailable",
        "The App Store is not answering. Nothing here can be bought until it does — and nothing you already own has changed."
    )
    static let verifyLater = res(
        "paywall.verifyLater",
        "Apple has taken the payment. We could not confirm it this second — it will open by itself shortly, and nothing is lost."
    )
    static let refused = res(
        "paywall.refused", "That purchase is not the one that was asked for. Nothing extra has been charged."
    )
    static let withdrawn = res(
        "paywall.withdrawn",
        "Apple has taken that purchase back — refunded or revoked — so nothing is open under it."
    )
    static let notVerified = res(
        "paywall.notVerified",
        "That purchase could not be verified, so nothing has been opened. If Apple charged you, write to us and we will sort it out."
    )
    static let offline = res(
        "paywall.offline",
        "Alma is not answering right now, so the purchase could not be confirmed. It will open by itself once she does."
    )

    // MARK: — owning things

    static let owned = res("paywall.owned", "yours")
    static let ownedAll = res("paywall.ownedAll", "Everything is open. All forty-one chapters are yours.")

    // MARK: — the store's own terms

    static let manage = res("paywall.manage", "Manage your subscription")
    static let manageNote = res(
        "paywall.manageNote", "Plans bought in the app are cancelled in your Apple ID settings, not here."
    )
    static let autoRenewTerms = res(
        "paywall.autoRenewTerms",
        "Payment is charged to your Apple ID when you confirm. The plan renews automatically unless you cancel at least 24 hours before the period ends, and the renewal is charged within the 24 hours before it. Manage or cancel it in your Apple ID settings."
    )
    static let terms = res("paywall.terms", "Terms")
    static let privacy = res("paywall.privacy", "Privacy Policy")
    static let subscriptionTerms = res("paywall.subscriptionTerms", "Subscription terms")

    static let honestyOnce = res("paywall.honestyOnce", "one-time is one-time")
    static let honestySeller = res("paywall.honestySeller", "Apple takes the payment and sends the receipt")
    static let honestyCancel = res("paywall.honestyCancel", "cancel in your Apple ID settings")

    /// One place that knows which table these live in.
    ///
    /// Written as a function rather than repeated forty-seven times because
    /// `table: "Paywall"` typed forty-seven times is forty-seven chances to type
    /// it once as `"paywall"` — which does not fail to build, it ships the key
    /// itself to every language including English.
    private static func res(
        _ key: StaticString, _ english: String.LocalizationValue
    ) -> LocalizedStringResource {
        LocalizedStringResource(key, defaultValue: english, table: "Paywall")
    }
}
