import Foundation

/// Every string the six late screens show, named.
///
/// **A fifth String Catalog.** `Localizable` belongs to the shell, `Cabinet` to
/// the cabinet, `Journey` to the journey and `Paywall` to the ladder; this one
/// belongs to the Alma tab, one saved conversation, sign-in, the legal reader,
/// the people list and add-a-person. A catalog is one JSON document with one
/// `strings` object, so a table per owner is what makes two people editing at
/// once safe — and `LocalizedStringResource` takes a table name, so the cost is
/// one argument, paid here and at no call site.
///
/// The same rule as everywhere else in this app: a constant per string, never a
/// key spelled at the call site. A misspelled key does not fail the build — it
/// ships the key itself, in English, to Brazil.
///
/// Generated by `tools/gen_screens_strings.py`. Add a key there, not by hand in
/// the JSON, which is where a missing language hides.
enum ScreenL10n {

    static let table = "Screens"

    // Written out per constant rather than through a helper, and not by
    // choice: `LocalizedStringResource(_:defaultValue:table:)` takes a
    // `StaticString` key, so a key assembled at runtime does not compile. That
    // is the right restriction — it is what lets Xcode's string extraction see
    // every key — but it means the table name is repeated on each line.

    // MARK: — the Alma tab

    static let chatOpening = LocalizedStringResource("scr.chat.opening", defaultValue: "Ask me anything about your chart. I answer from what is in it, and I say so when the answer is not.", table: table)
    static let chatNoChart = LocalizedStringResource("scr.chat.noChart", defaultValue: "I can talk without your chart, but I would only be guessing. Give me your birth data and I can read you instead.", table: table)
    static let chatRule = LocalizedStringResource("scr.chat.rule", defaultValue: "Every answer names the placements it was read from. Nothing here is a prediction.", table: table)

    /// Three questions worth asking, so that an empty field is not the whole
    /// invitation. Taken from the web app's own prompt list.
    ///
    /// These are the **fallback**. `ChatOpeners` prefers three questions about
    /// this person's own sun, moon and rising, which the free natal preview
    /// already carries; these stand in until it arrives, and for anybody whose
    /// chart could not be fetched.
    static let chatPrompts: [LocalizedStringResource] = [
        LocalizedStringResource("scr.chat.prompt1", defaultValue: "What am I like when nobody is watching?", table: table),
        LocalizedStringResource("scr.chat.prompt2", defaultValue: "What is crossing my chart this week?", table: table),
        LocalizedStringResource("scr.chat.prompt3", defaultValue: "Where do my systems disagree about me?", table: table),
    ]

    static let askPlaceholder = LocalizedStringResource("scr.chat.placeholder", defaultValue: "Ask Alma", table: table)
    static let send = LocalizedStringResource("scr.chat.send", defaultValue: "Send", table: table)
    static let thinking = LocalizedStringResource("scr.chat.thinking", defaultValue: "Alma is reading your chart", table: table)
    static let thinkingStill = LocalizedStringResource("scr.chat.thinkingStill", defaultValue: "Still reading — she does not skim.", table: table)

    /// The footnote that replaced `scr.chat.notFromChart`.
    ///
    /// The old key was an uppercase tag reading NOT FROM YOUR CHART, and it was
    /// shown whenever `answered_from_chart` was false — which included every
    /// greeting she declined to treat as a question, so a person who typed
    /// "hello" was told their hello was not in their chart. This one is a
    /// sentence, in her voice, shown only when the server names the turn
    /// `chart_silent`.
    static let chatSilent = LocalizedStringResource("scr.chat.silent", defaultValue: "I answered that one from what I know, not from your chart.", table: table)

    static let chatCouldAsk = LocalizedStringResource("scr.chat.couldAsk", defaultValue: "you could ask", table: table)
    static let chatReadFromAll = LocalizedStringResource("scr.chat.readFromAll", defaultValue: "Show every placement this was read from", table: table)

    /// The openers, each about a sign this person actually has. `sign` is
    /// already translated by the caller — the engine's sign names are English
    /// keys in every locale.
    static func chatPromptMoon(_ sign: String) -> LocalizedStringResource {
        LocalizedStringResource("scr.chat.promptMoon", defaultValue: "My Moon is in \(sign). What does it actually need?", table: table)
    }

    static func chatPromptSun(_ sign: String) -> LocalizedStringResource {
        LocalizedStringResource("scr.chat.promptSun", defaultValue: "My Sun is in \(sign) — what does that ask of me?", table: table)
    }

    static func chatPromptRising(_ sign: String) -> LocalizedStringResource {
        LocalizedStringResource("scr.chat.promptRising", defaultValue: "\(sign) rising. Is that what people meet first?", table: table)
    }

    /// What this screen says instead of a status code. Every one of them is in
    /// the first person and every one of them says the question was not lost,
    /// because it is not: `ChatModel.send` puts it back in the field.
    static let chatRefused = LocalizedStringResource("scr.chat.refused", defaultValue: "I could not answer that one without inventing a placement, so I did not. Ask it another way and I will try again.", table: table)
    static let chatOffline = LocalizedStringResource("scr.chat.offline", defaultValue: "I cannot reach your chart just now. Your question is still in the box — try again in a moment.", table: table)
    static let chatUnavailable = LocalizedStringResource("scr.chat.unavailable", defaultValue: "Something on my side is not working. Your chart is untouched, and your question is still in the box.", table: table)
    static let chatWentWrong = LocalizedStringResource("scr.chat.wentWrong", defaultValue: "That did not go through. Nothing was lost — your question is still in the box.", table: table)
    static let chatOutOfQuestions = LocalizedStringResource("scr.chat.outOfQuestions", defaultValue: "That was your free conversation. The plan carries it on — with the morning notification and your day written out.", table: table)

    static let moreQuestions = LocalizedStringResource("scr.chat.moreQuestions", defaultValue: "More questions", table: table)
    static let pastQuestions = LocalizedStringResource("scr.chat.past", defaultValue: "earlier", table: table)
    static let untitledThread = LocalizedStringResource("scr.chat.untitled", defaultValue: "Untitled conversation", table: table)

    // MARK: — sign in

    static let signInEyebrow = LocalizedStringResource("scr.signIn.eyebrow", defaultValue: "your account", table: table)
    static let signInTitle = LocalizedStringResource("scr.signIn.title", defaultValue: "Sign in", table: table)
    static let signInLead = LocalizedStringResource("scr.signIn.lead", defaultValue: "Signing in attaches a name to the account you already have. Nothing you have read or bought is lost — it is the same account, made durable.", table: table)

    static let signInReasons: [LocalizedStringResource] = [
        LocalizedStringResource("scr.signIn.reason1", defaultValue: "Your chart survives a new phone.", table: table),
        LocalizedStringResource("scr.signIn.reason2", defaultValue: "Anything you bought can be restored. A purchase belongs to the account that claimed it first, so sign in before you reinstall.", table: table),
        LocalizedStringResource("scr.signIn.reason3", defaultValue: "There is no password. There never will be.", table: table),
    ]

    static let orByEmail = LocalizedStringResource("scr.signIn.orEmail", defaultValue: "or by email", table: table)
    static let emailPlaceholder = LocalizedStringResource("scr.signIn.emailPlaceholder", defaultValue: "Your email address", table: table)
    static let sendLink = LocalizedStringResource("scr.signIn.sendLink", defaultValue: "Send me a link", table: table)
    static let sending = LocalizedStringResource("scr.signIn.sending", defaultValue: "Sending…", table: table)
    static let linkSent = LocalizedStringResource("scr.signIn.linkSent", defaultValue: "Check your inbox. The link signs you in and expires shortly.", table: table)
    static let continueWithGoogle = LocalizedStringResource("scr.signIn.google", defaultValue: "Continue with Google", table: table)
    static let signInFailed = LocalizedStringResource("scr.signIn.failed", defaultValue: "That did not sign you in. Nothing has changed on your account.", table: table)
    static let signedIn = LocalizedStringResource("scr.signIn.done", defaultValue: "You are signed in.", table: table)
    static let signedInAlready = LocalizedStringResource("scr.signIn.already", defaultValue: "You are already signed in. This account follows you to any phone.", table: table)
    static let signInPrivacy = LocalizedStringResource("scr.signIn.privacy", defaultValue: "We use your address for the sign-in link and nothing else. There is no newsletter.", table: table)
    static let done = LocalizedStringResource("scr.done", defaultValue: "Done", table: table)

    // MARK: — people

    static let peopleEyebrow = LocalizedStringResource("scr.people.eyebrow", defaultValue: "compatibility", table: table)
    static let peopleTitle = LocalizedStringResource("scr.people.title", defaultValue: "People", table: table)
    static let peopleLead = LocalizedStringResource("scr.people.lead", defaultValue: "Compatibility compares your chart against somebody else's. The comparison itself is calculated free, as every calculation is.", table: table)
    static let peopleSaved = LocalizedStringResource("scr.people.saved", defaultValue: "saved", table: table)
    static let peopleConsent = LocalizedStringResource("scr.people.consent", defaultValue: "It is their birth data, not yours. Ask them first.", table: table)
    static let unnamedPerson = LocalizedStringResource("scr.people.unnamed", defaultValue: "Unnamed", table: table)
    static let remove = LocalizedStringResource("scr.people.remove", defaultValue: "Remove", table: table)
    static let removePerson = LocalizedStringResource("scr.people.remove", defaultValue: "Remove", table: table)
    static let removePersonTitle = LocalizedStringResource("scr.people.removeTitle", defaultValue: "Remove this person?", table: table)
    static let removePersonWhat = LocalizedStringResource("scr.people.removeWhat", defaultValue: "Their birth goes, and so does every compatibility reading written from it. Readings you paid for cannot be written again word for word.", table: table)
    static let keep = LocalizedStringResource("scr.keep", defaultValue: "Keep", table: table)

    static let addPersonTimeUnknown = LocalizedStringResource("scr.addPerson.timeUnknown", defaultValue: "Birth time unknown", table: table)
    static let addPersonEyebrow = LocalizedStringResource("scr.addPerson.eyebrow", defaultValue: "a second birth", table: table)
    static let addPersonTitle = LocalizedStringResource("scr.addPerson.title", defaultValue: "Add a person", table: table)
    static let addPersonLead = LocalizedStringResource("scr.addPerson.lead", defaultValue: "The same five things your own chart needed. Without the minute of birth the comparison still runs, on fewer factors.", table: table)
    static let theirName = LocalizedStringResource("scr.addPerson.name", defaultValue: "their name", table: table)
    static let namePlaceholder = LocalizedStringResource("scr.addPerson.namePlaceholder", defaultValue: "Name", table: table)
    static let relationPlaceholder = LocalizedStringResource("scr.addPerson.relationPlaceholder", defaultValue: "Partner, mother, friend… (optional)", table: table)
    static let theirBirthday = LocalizedStringResource("scr.addPerson.birthday", defaultValue: "their birthday", table: table)
    static let theirBirthTime = LocalizedStringResource("scr.addPerson.birthTime", defaultValue: "their birth time", table: table)
    static let theirBirthplace = LocalizedStringResource("scr.addPerson.birthplace", defaultValue: "their birthplace", table: table)
    static let savePerson = LocalizedStringResource("scr.addPerson.save", defaultValue: "Save this person", table: table)
    static let saving = LocalizedStringResource("scr.addPerson.saving", defaultValue: "Saving…", table: table)

    // MARK: — compatibility, with a name on it

    static func comparedWith(_ name: String) -> LocalizedStringResource {
        LocalizedStringResource("scr.compat.readAgainst", defaultValue: "Compared with \(name)", table: table)
    }

    static let chooseSomebodyElse = LocalizedStringResource("scr.compat.choose", defaultValue: "Compare with somebody else", table: table)

    // MARK: — the empty state that has to make the 4.3(b) argument

    static let emptyTitle = LocalizedStringResource("scr.empty.title", defaultValue: "Eight systems, one chart", table: table)
    static let emptyLead = LocalizedStringResource("scr.empty.lead", defaultValue: "Alma computes eight independent systems from a real JPL ephemeris — forty-one chapters in all — and shows where three of them agree about you and where they do not.", table: table)
    static let emptyExample = LocalizedStringResource("scr.empty.example", defaultValue: "what a line looks like", table: table)
    static let emptyExampleNote = LocalizedStringResource("scr.empty.exampleNote", defaultValue: "Every sentence Alma writes names the placement it was read from, like the one above. Nothing is a prediction, and nothing is shown that was not calculated.", table: table)
    static let exampleTag = LocalizedStringResource("scr.empty.exampleTag", defaultValue: "example — not your chart", table: table)

    /// The portrait's note under its free values.
    ///
    /// The web's says "These two systems never cost anything" and sits under
    /// three rows — numerology, the birth card, and the moon phase, which is
    /// free because it falls out of the natal preview. On the one screen whose
    /// whole job is to prove the numbers are carefully computed, an off-by-one
    /// is the worst possible detail to leave in. This one counts nothing, so it
    /// stays true however many values could be read for a given birth.
    static let portraitFreeNote = LocalizedStringResource("scr.journey.freeNote", defaultValue: "Every number above is calculated, and calculated is always free. They are yours whether you read further or not.", table: table)

    static func chapters(_ count: Int) -> LocalizedStringResource {
        LocalizedStringResource("scr.empty.chapters", defaultValue: "\(count) chapters", table: table)
    }
}
