"""Persistence — models, session management and the repository helpers."""

from .models import (
    AuthProvider,
    Base,
    CalcCacheEntry,
    ChatMessage,
    ChatThread,
    DeviceToken,
    Entitlement,
    EntitlementKind,
    Event,
    MagicLink,
    Memory,
    Profile,
    Purchase,
    Reading,
    Setting,
    UsageCounter,
    User,
    WebhookEvent,
    new_id,
    utcnow,
)
from .session import (
    create_all,
    dispose,
    drop_all,
    engine,
    get_session,
    healthy,
    session_factory,
    session_scope,
)

__all__ = [
    "AuthProvider",
    "Base",
    "CalcCacheEntry",
    "ChatMessage",
    "ChatThread",
    "DeviceToken",
    "Entitlement",
    "EntitlementKind",
    "Event",
    "MagicLink",
    "Memory",
    "Profile",
    "Purchase",
    "Reading",
    "Setting",
    "UsageCounter",
    "User",
    "WebhookEvent",
    "create_all",
    "dispose",
    "drop_all",
    "engine",
    "get_session",
    "healthy",
    "new_id",
    "session_factory",
    "session_scope",
    "utcnow",
]
